import {templates,initial,move,flip,isolated,equation,sideTex,operationTex} from './motor.mjs';
import {m,render,feedback} from '../cierre/ui.mjs';
import {rnd} from '../motor.mjs';
const $=s=>document.querySelector(s);
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function animateChanges(before,selector){if(reduced())return;document.querySelectorAll(selector).forEach(el=>{const old=before.get(el.dataset.factor||el.dataset.half);if(!old)return;const now=el.getBoundingClientRect();el.animate([{transform:`translate(${old.x-now.x}px,${old.y-now.y}px)`,background:'#fff0bc'},{transform:'translate(0,0)'}],{duration:420,easing:'ease-out'});});}
function positions(selector){return new Map([...document.querySelectorAll(selector)].map(el=>[el.dataset.factor||el.dataset.half,el.getBoundingClientRect()]));}
// Swapping whole sides is separate from taking reciprocals.
let flipCase=0,swapped=false;
const flipExamples=[['x','5'],['3x','12'],['\\frac{a}{b}','\\frac{c}{d}']];
$('#flip-demo').innerHTML='<div class="side-labels"><span>Izquierda</span><span>Derecha</span></div><div id="flip-equation" class="equation-board"></div><div class="actions"><button id="flip-example">⇄ Voltear</button><button id="next-flip" class="secondary">Otro ejemplo</button></div><p id="flip-message" class="small-note" role="status"></p>';
function drawFlip(){const [left,right]=flipExamples[flipCase];$('#flip-equation').innerHTML=`<div data-half="${swapped?'b':'a'}">${m(swapped?right:left)}</div><span class="equals">=</span><div data-half="${swapped?'a':'b'}">${m(swapped?left:right)}</div>`;render();}
$('#flip-example').onclick=()=>{const before=positions('[data-half]');swapped=!swapped;drawFlip();animateChanges(before,'[data-half]');$('#flip-message').textContent='Los lados cambiaron de posición. La igualdad sigue siendo la misma.';};
$('#next-flip').onclick=()=>{flipCase=(flipCase+1)%flipExamples.length;swapped=false;drawFlip();$('#flip-message').textContent='';};drawFlip();
const numericKinds=[{name:'Suma',a:7,b:12},{name:'Resta',a:4,b:9},{name:'Multiplicación',a:3,b:12},{name:'División',a:5,b:7}];let numericKind=0,example={...numericKinds[0]};
$('#numeric-demo').innerHTML='<div class="mode-buttons">'+numericKinds.map((x,i)=>`<button data-numeric="${i}" aria-pressed="${i===0}">${x.name}</button>`).join('')+'</div><div id="numeric-work"></div><button id="numeric-new" class="secondary">Otro ejemplo numérico ↻</button>';
function numeric(){const {a,b}=example,k=numericKind;feedback('numeric-feedback','');const token=`<button id="numeric-token" aria-label="Seleccionar ${a}" aria-pressed="false">${m(String(a))}</button>`;const left=k===0?m('x')+' + '+token:k===1?m('x')+' − '+token:k===2?token+' · '+m('x'):`<span class="fraction"><span>${m('x')}</span><span>${token}</span></span>`;
 $('#numeric-work').innerHTML=`<p>Deja sola ${m('x')}. Pulsa el ${a} que la acompaña.</p><div class="numeric-equation">${left}<span>=</span>${m(String(b))}</div><div id="numeric-operation"></div><div id="numeric-proof"></div>`;
 const result=k===0?b-a:k===1?b+a:k===2?b/a:b*a,verb=k===0?'Restar':k===1?'Sumar':k===2?'Dividir entre':'Multiplicar por';
 const both=k===0?`x+${a}-${a}=${b}-${a}`:k===1?`x-${a}+${a}=${b}+${a}`:k===2?`\\frac{${a}x}{${a}}=\\frac{${b}}{${a}}`:`\\frac{x}{${a}}\\cdot ${a}=${b}\\cdot ${a}`;
 const simplified=k===0?`x=${b}-${a}`:k===1?`x=${b}+${a}`:k===2?`x=\\frac{${b}}{${a}}`:`x=${b}\\cdot ${a}`;
 $('#numeric-token').onclick=()=>{$('#numeric-token').setAttribute('aria-pressed','true');$('#numeric-operation').innerHTML=`<button id="apply-numeric">${verb} ${a} en ambos lados</button>`;$('#apply-numeric').onclick=()=>{$('#numeric-token').disabled=true;$('#apply-numeric').disabled=true;$('#numeric-proof').innerHTML='<div class="same-operation"><p>La misma operación en ambos lados:</p>'+m(both)+'</div><div class="numeric-equation">'+m(simplified)+'</div><div class="answer-row"><label for="numeric-answer">Calcula el valor de x</label><input id="numeric-answer" class="numeric-input" inputmode="numeric" autocomplete="off"><button id="numeric-check">Comprobar</button></div>';render();if(!reduced())$('#numeric-proof').animate([{opacity:0,transform:'translateY(-8px)'},{opacity:1,transform:'translateY(0)'}],{duration:300});$('#numeric-answer').focus({preventScroll:true});$('#numeric-check').onclick=()=>{const text=$('#numeric-answer').value.trim();if(!/^-?\d+$/.test(text))return feedback('numeric-feedback','Escribe el resultado como un número entero.');feedback('numeric-feedback',+text===result?'✓ ¡Correcto! '+m('x='+result)+'. La igualdad se conserva.':'La transformación ya es correcta. Revisa solamente la cuenta final.',+text===result);};$('#numeric-answer').onkeydown=e=>{if(e.key==='Enter')$('#numeric-check').click();};};};render();}
 document.querySelectorAll('[data-numeric]').forEach(button=>button.onclick=()=>{numericKind=+button.dataset.numeric;example={...numericKinds[numericKind]};document.querySelectorAll('[data-numeric]').forEach(x=>x.setAttribute('aria-pressed',x===button));numeric();});$('#numeric-new').onclick=()=>{const a=rnd(2,9),x=rnd(2,9);example={a,b:numericKind===0?x+a:numericKind===1?x:numericKind===2?a*x:x};numeric();};numeric();
function fractionExample(target){const lines=target==='a'?['\\frac{a}{b}=\\frac{c}{d}','\\frac{a}{b}\\cdot b=\\frac{c}{d}\\cdot b','a=\\frac{b\\cdot c}{d}']:['\\frac{a}{b}=\\frac{c}{d}','\\frac{a}{b}\\cdot d=\\frac{c}{d}\\cdot d','\\frac{a\\cdot d}{b}=c','c=\\frac{a\\cdot d}{b}'];$('#fraction-example').innerHTML='<div class="worked">'+lines.map(t=>'<div>'+m(t)+'</div>').join('<span aria-hidden="true">↓</span>')+'</div><p>'+(target==='a'?'Multiplicamos ambos lados por b y simplificamos.':'Multiplicamos ambos lados por d, simplificamos y volteamos la igualdad.')+'</p>';render();}
 document.querySelectorAll('[data-example]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-example]').forEach(x=>x.setAttribute('aria-pressed',x===button));fractionExample(button.dataset.example);});fractionExample('a');
const emojiSets=[['🍎','🍐','🍌','🍊','🍇'],['⭐','🌙','☀️','🌎','🪐'],['🐟','🐙','🦀','🐚','🐬'],['🔵','🔺','🟩','💎','🟣']];
let shape=0,state=initial(),target='a',emojiMode=true,emojiSet=0,history=[],selected=null,proof='';
const label=id=>emojiMode?emojiSets[emojiSet][id.charCodeAt(0)-97]:id;
const piece=id=>emojiMode?`<span class="emoji" aria-hidden="true">${label(id)}</span>`:m(id);
$('#equation-lab').innerHTML='<label for="structure">Estructura</label><select id="structure">'+templates.map((t,i)=>`<option value="${i}">${t.name}</option>`).join('')+'</select><div class="lab-goal" id="lab-goal"></div><div id="target-buttons" class="target-buttons" role="group" aria-label="Cantidad que quieres despejar"></div><div class="side-labels"><span>Izquierda</span><span>Derecha</span></div><div id="live-equation" class="equation-board"></div><div id="operation-menu" class="operation-menu"></div><div class="actions"><button id="flip-lab">⇄ Voltear</button><button id="undo" class="secondary">↶ Deshacer</button><button id="reset" class="secondary">Reiniciar</button></div><div class="actions"><button id="representation" class="secondary">Ver con letras</button><button id="new-goal" class="secondary">Otro objetivo ↻</button><button id="new-symbols" class="secondary">Otros símbolos</button></div><div id="mapping" class="mapping"></div><div id="operation-proof" aria-live="polite"></div><div id="letter-result"></div>';
function sideHTML(side){const items=state.filter(x=>x.side===side);function product(power){return items.filter(x=>x.power===power).map(x=>`<button data-factor="${x.id}" class="factor-token ${selected===x.id?'selected':''}" aria-label="Seleccionar ${x.id}${emojiMode?', '+label(x.id):''}, ${power===1?'numerador':'denominador'} del lado ${side===0?'izquierdo':'derecho'}" aria-pressed="${selected===x.id}">${piece(x.id)}</button>`).join('<span class="times" aria-hidden="true">·</span>')||m('1');}const denominator=items.some(x=>x.power===-1);return denominator?`<span class="fraction interactive-fraction"><span>${product(1)}</span><span>${product(-1)}</span></span>`:product(1);}
function remember(){history.push({state:state.map(x=>({...x})),proof});}
function draw(){const done=isolated(state,target);$('#lab-goal').innerHTML='<span>Deja sola esta cantidad:</span><strong>'+piece(target)+' = ?</strong>';$('#target-buttons').innerHTML=initial(shape).map(x=>`<button data-target="${x.id}" class="secondary" aria-label="Despejar ${x.id}${emojiMode?', '+label(x.id):''}" aria-pressed="${target===x.id}">${piece(x.id)}</button>`).join('');$('#live-equation').innerHTML='<div class="equation-side">'+sideHTML(0)+'</div><span class="equals">=</span><div class="equation-side">'+sideHTML(1)+'</div>';$('#operation-proof').innerHTML=proof;$('#undo').disabled=history.length===0;$('#representation').textContent=emojiMode?'Ver con letras':'Ver con emojis';$('#representation').setAttribute('aria-pressed',!emojiMode);$('#new-symbols').disabled=!emojiMode;$('#mapping').innerHTML=initial(shape).map(x=>'<span>'+emojiSets[emojiSet][x.id.charCodeAt(0)-97]+' ↔ '+m(x.id)+'</span>').join('');$('#letter-result').innerHTML=done?'<div class="solved"><strong>La cantidad ya está sola.</strong><p>La misma transformación con letras:</p><div class="numeric-equation">'+m(equation(state))+'</div></div>':'';
 if(done)feedback('lab-feedback',state.find(x=>x.id===target).side===0?'✓ ¡Correcto! Aislaste la cantidad buscada.':'✓ La cantidad ya está aislada a la derecha. Puedes voltear la igualdad para escribirla a la izquierda.',true);else feedback('lab-feedback','');
 document.querySelectorAll('[data-target]').forEach(button=>button.onclick=()=>{target=button.dataset.target;reset();});document.querySelectorAll('[data-factor]').forEach(button=>button.onclick=()=>{selected=button.dataset.factor;document.querySelectorAll('[data-factor]').forEach(x=>{x.classList.toggle('selected',x===button);x.setAttribute('aria-pressed',x===button);});const item=state.find(x=>x.id===selected),verb=item.power===1?'Dividir entre':'Multiplicar por';$('#operation-menu').innerHTML='<p>Elegiste '+piece(item.id)+', que está '+(item.power===1?'multiplicando en el numerador.':'dividiendo en el denominador.')+'</p><button id="apply-factor">'+verb+' '+(emojiMode?label(item.id):item.id)+' en ambos lados</button>';$('#apply-factor').onclick=()=>{const id=selected,before=positions('[data-factor]'),old=state;remember();state=move(state,id);proof='<div class="same-operation"><p>'+verb+' '+m(id)+' en ambos lados:</p>'+m(operationTex(old,id))+'<span class="proof-arrow" aria-hidden="true">↓</span>'+m(equation(state))+'</div>';selected=null;$('#operation-menu').innerHTML='';draw();animateChanges(before,'[data-factor]');document.querySelector(`[data-factor="${id}"]`)?.focus({preventScroll:true});if(!isolated(state,target))feedback('lab-feedback','✓ Operación equivalente. Sigue eliminando los factores que acompañan a la cantidad buscada.',true);};render();});render();}
function reset(){state=initial(shape);history=[];selected=null;proof='';$('#operation-menu').innerHTML='';draw();}
$('#structure').onchange=()=>{shape=+$('#structure').value;const available=initial(shape);target=available[rnd(0,available.length-1)].id;reset();};
$('#flip-lab').onclick=()=>{const before=positions('[data-factor]');remember();state=flip(state);selected=null;$('#operation-menu').innerHTML='';proof='<div class="same-operation"><p>Intercambiamos los lados, sin cambiar signos ni invertir fracciones.</p>'+m(equation(state))+'</div>';draw();animateChanges(before,'[data-factor]');};
$('#undo').onclick=()=>{const previous=history.pop();if(!previous)return;state=previous.state;proof=previous.proof;selected=null;$('#operation-menu').innerHTML='';draw();};
$('#reset').onclick=reset;
$('#representation').onclick=()=>{emojiMode=!emojiMode;selected=null;$('#operation-menu').innerHTML='';draw();};
$('#new-goal').onclick=()=>{const available=initial(shape),index=available.findIndex(x=>x.id===target);target=available[(index+1)%available.length].id;reset();};
$('#new-symbols').onclick=()=>{emojiSet=(emojiSet+1)%emojiSets.length;selected=null;$('#operation-menu').innerHTML='';draw();};
draw();render();
