import test from 'node:test';
import assert from 'node:assert/strict';
import {create,generate,initial,transition,evaluate,equationTex,solved,check,blocks} from './motor.mjs';
const go=(s,ids,action)=>{const before=JSON.stringify(s),r=transition(s,ids,action);assert.ok(r.ok,r.message);assert.equal(JSON.stringify(s),before);assert.ok(Math.abs(evaluate(r.state.left,s.solution)-evaluate(r.state.right,s.solution))<1e-8);return r.state;};
test('reversible constants, both members and reordering',()=>{let s=create(3,5,8,2);const start=equationTex(s);s=go(s,['c'],'restar');assert.match(equationTex(s),/-17=0/);s=go(s,['c'],'sumar');assert.equal(equationTex(s),start);s=go(s,['b'],'restar');s=go(s,['b'],'sumar');assert.equal(equationTex(s),start);s=go(s,['x','b'],'reordenar');assert.match(equationTex(s),/^5\+/);s=go(s,['x','b'],'reordenar');assert.equal(equationTex(s),start);});
test('accumulate denominator and numerator without combining, reverse both',()=>{let s=create(3,0,8,2),start=equationTex(s);s=go(s,['den'],'multiplicar');s=go(s,['a'],'dividir');assert.equal(equationTex(s),'x=\\frac{12\\cdot 2}{3}');s=go(s,['a'],'multiplicar');s=go(s,['den'],'dividir');assert.equal(evaluate(s.left,8),12);assert.equal(evaluate(s.right,8),12);assert.ok(blocks(s).some(b=>b.id==='a'&&b.side==='left'));});
test('uncombined subtraction remains grouped during scaling',()=>{let s=create(3,5,8,2);s=go(s,['b'],'restar');s=go(s,['den'],'multiplicar');s=go(s,['a'],'dividir');assert.equal(equationTex(s),'x=\\frac{\\left(17-5\\right)\\cdot 2}{3}');s=go(s,['c','b'],'combinar');const n=blocks(s).find(b=>b.id.startsWith('n')).id;s=go(s,[n,'den'],'combinar');const m=blocks(s).find(b=>b.id.startsWith('n')).id;s=go(s,[m,'a'],'combinar');assert.ok(solved(s));assert.ok(check(s,'8'));assert.deepEqual(initial(s),create(3,5,8,2));});
test('incorrect moves, zero division and incompatible pairs are rejected unchanged',()=>{for(const [s,ids,a] of [[create(3,5,8,2),['a'],'dividir'],[create(3,5,8,2),['den'],'multiplicar'],[create(3,5,8,2),['b'],'sumar'],[create(3,0,0,2),['c'],'dividir'],[create(3,5,8,2),['a','b'],'combinar']]){const r=transition(s,ids,a);assert.equal(r.ok,false);assert.equal(r.state,s);}});
test('generated equations and random legal exploration preserve affine equality',()=>{for(let i=0;i<1500;i++){let s=generate();assert.ok(s.solution>=-20&&s.solution<=20);for(let j=0;j<25;j++){const bs=blocks(s);const a=['sumar','restar','multiplicar','dividir','combinar','reordenar'][Math.floor(Math.random()*6)];const ids=[bs[Math.floor(Math.random()*bs.length)].id];if(a==='combinar'||a==='reordenar')ids.push(bs[Math.floor(Math.random()*bs.length)].id);const r=transition(s,ids,a);if(r.ok){assert.ok(Math.abs(evaluate(r.state.left,s.solution)-evaluate(r.state.right,s.solution))<1e-7);for(const x of [-7,0,11]){const old=evaluate(s.left,x)-evaluate(s.right,x),now=evaluate(r.state.left,x)-evaluate(r.state.right,x);assert.equal(Math.abs(old)<1e-9,Math.abs(now)<1e-9);}s=r.state;}}}});

test('x crosses as a full summand and as a nonzero factor reversibly',()=>{let s=create(2,3,4);s=go(s,['x'],'restar');assert.equal(equationTex(s),'3=11-2x');s=go(s,['x'],'sumar');assert.equal(evaluate(s.left,4),11);s=create(2,0,4);s=go(s,['x'],'dividir');assert.equal(equationTex(s),'2=\\frac{8}{x}');assert.equal(s.nonzeroX,true);s=go(s,['x'],'multiplicar');assert.equal(evaluate(s.left,4),8);const z=create(2,0,0);assert.equal(transition(z,['x'],'dividir').state,z);});
test('empty members and neutral identities',()=>{let s=create(1,0,4);s=go(s,['x'],'restar');assert.equal(equationTex(s),'0=4-x');s=go(s,['x'],'sumar');assert.equal(equationTex(s),'x=4');s=create(2,0,4);s=go(s,['a'],'dividir');s=go(s,['x'],'dividir');assert.equal(equationTex(s),'1=\\frac{8}{2x}');s=go(s,['x'],'multiplicar');assert.equal(equationTex(s),'x=\\frac{8}{2}');});
