import {expandLessons} from './explicaciones.mjs';
export const formula=(tex,html)=>`<div class="formula"><span data-tex="${tex.replaceAll('"','&quot;')}">${html}</span></div>`;
const F=formula;
const idea=s=>`<p class="idea">${s}</p>`;
const example=s=>`<div class="everyday"><strong>En la vida diaria</strong><p>${s}</p></div>`;
const terms=items=>`<dl class="terms">${items.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl>`;
const q=(prompt,options,answer,why)=>({prompt,options,answer,why});
export const pages=[
 {slug:'',key:'joule',title:'Electricidad 3',heading:'La corriente también calienta',intro:'Vamos a entender qué ocurre dentro de los circuitos. Explora, observa y explica las ideas con tus propias palabras.',
 body:`<h2>Efecto Joule</h2><p>Cuando una corriente atraviesa un material con resistencia, la energía eléctrica se transforma en energía térmica: el material se calienta.</p><p>El campo eléctrico impulsa a los electrones de conducción. Al interactuar con la estructura del material —imagínalo como encuentros con sus átomos— transfieren energía. Los átomos vibran más y aumenta la temperatura.</p>${idea('Se transforma la <strong>energía</strong>. La corriente no se convierte en calor ni los electrones se consumen.')}<div data-lab="joule"></div>${F('P=I^{2}R','P = I<sup>2</sup>R')}${terms([['P','Potencia térmica: energía transformada por segundo (W).'],['I','Corriente eléctrica (A).'],['R','Resistencia del elemento (Ω).']])}<p><strong>A corriente fija</strong>, más resistencia produce más calentamiento por segundo. A resistencia fija, más corriente también lo aumenta.</p><details><summary>¿Y si mantengo fijo el voltaje?</summary>${F('P=\\frac{V^{2}}{R}','P = V²/R')}<p>Con el mismo voltaje, aumentar R reduce la corriente y la potencia. Siempre hay que decir qué magnitud se mantiene fija.</p></details>${example('La resistencia de una tostadora se calienta a propósito. En los cables también aparece calor; por eso no conviene que una corriente grande atraviese un cable demasiado delgado.')}`,
 questions:[q('¿Qué ocurre en el efecto Joule?',['La energía eléctrica se transforma en energía térmica.','La carga eléctrica desaparece.','Los átomos se convierten en electrones.'],0,'La energía pasa al material. La carga no se consume.'),q('Si la corriente se mantiene igual y aumenta R, ¿qué ocurre con la potencia térmica?',['Disminuye.','Aumenta.','Siempre queda igual.'],1,'Con I fija, P = I²R aumenta al aumentar R. Esta comparación no supone voltaje fijo.')]
 },
 {slug:'nodos',key:'nodos',title:'La corriente se reparte',heading:'Primera ley de Kirchhoff',intro:'Un nodo es un punto de unión entre ramas del circuito. Allí la carga puede seguir distintos caminos.',
 body:`<p>Las flechas indican el sentido de la <strong>corriente convencional</strong>. Una flecha hacia el nodo entra; una que se aleja sale.</p><div data-lab="nodos"></div>${F('\\sum I_{\\mathrm{entrada}}=\\sum I_{\\mathrm{salida}}','Σ I<sub>entrada</sub> = Σ I<sub>salida</sub>')}${idea('<strong>Lo que entra debe salir.</strong> En régimen estable, el nodo no acumula carga. La ley expresa conservación de la carga eléctrica.')}<p>Σ significa «suma». I representa corriente y se mide en amperes (A).</p>${example('En una instalación, una línea puede alimentar dos aparatos por ramas diferentes. La corriente de la línea se reparte entre esas ramas. No se crea corriente extra en la unión.')}<details><summary>Corriente y electrones: ¿van hacia el mismo lado?</summary><p>En un metal, los electrones se desplazan en sentido contrario a la corriente convencional. Para leer estos diagramas seguimos las flechas de corriente convencional.</p></details>`,
 questions:[q('¿Qué principio representa la primera ley de Kirchhoff?',['Conservación de la energía.','Conservación de la carga eléctrica.','Creación de carga en las uniones.'],1,'La carga no se crea ni desaparece en el nodo.'),q('Llega corriente a una unión con dos salidas. ¿Qué debe cumplirse?',['Cada salida lleva toda la corriente de entrada.','Una salida debe llevar corriente nula.','Las dos corrientes de salida suman la corriente de entrada.'],2,'La corriente se reparte. No tiene que dividirse en partes iguales.')]
 },
 {slug:'mallas',key:'mallas',title:'Una vuelta completa',heading:'Segunda ley de Kirchhoff',intro:'Una trayectoria cerrada regresa al punto de partida. En este circuito sencillo, esa vuelta forma una malla.',
 body:`<p>La batería eleva el potencial. Las resistencias producen caídas de potencial al recorrerlas en el sentido de la corriente. Después de la vuelta completa, el cambio total debe ser cero.</p><div data-lab="mallas"></div>${F('\\sum \\Delta V=0','Σ ΔV = 0')}${F('\\varepsilon-I R_1-I R_2=0','ε − IR₁ − IR₂ = 0')}<p>En esta malla con una fuente: <strong>la subida ε equilibra las caídas IR₁ e IR₂</strong>. De ahí la forma Σ ε = Σ IR, con los signos correspondientes al recorrido.</p>${terms([['ε','Fem de la fuente, en volts (V).'],['I','Corriente, en amperes (A).'],['R₁, R₂','Resistencias, en ohms (Ω).'],['IR','Caída de voltaje en una resistencia, al seguir la corriente.']])}${idea('Segunda ley → <strong>malla, voltajes y conservación de la energía</strong>. La carga vuelve al punto de partida con el mismo potencial.')}<div class="compare"><div><h3>Primera ley</h3><p>Nodo · corrientes · carga</p></div><div><h3>Segunda ley</h3><p>Malla · voltajes · energía</p></div></div>${example('En una linterna encendida, la batería entrega energía por unidad de carga y el circuito la transforma. La energía no aparece de la nada al dar otra vuelta.')}<details><summary>¿De dónde salen los signos?</summary><p>Al cruzar la batería de − a +: +ε. Al atravesar una resistencia siguiendo la corriente: −IR. Si recorres esos elementos al revés, cambian los signos. Aquí usamos circuitos de corriente continua, sin un flujo magnético variable que atraviese la malla.</p></details>`,
 questions:[q('¿Qué ley usarías para hablar de subidas y caídas de voltaje en una vuelta cerrada?',['La primera ley: nodos.','La segunda ley: mallas.','La definición de capacitancia.'],1,'La segunda ley relaciona cambios de potencial y conservación de energía.'),q('En una vuelta cerrada, ¿cuál es la suma algebraica de los cambios de voltaje?',['Cero.','Siempre la fem de la batería.','La suma de las corrientes.'],0,'Al regresar al mismo punto recuperas el mismo potencial. Las subidas y caídas se equilibran.')]
 },
 {slug:'bateria-real',key:'bateria',title:'La batería real',heading:'No toda la energía llega al exterior',intro:'Una batería real se modela como una fuente ideal de fem ε y una resistencia interna r conectadas en serie.',
 body:`<div data-lab="bateria"></div>${F('I=\\frac{\\varepsilon}{R_T+r}','I = ε/(R<sub>T</sub> + r)')}${F('V_T=\\varepsilon-Ir','V<sub>T</sub> = ε − Ir')}${terms([['I','Intensidad de corriente (A).'],['ε','Fem: energía que la fuente aporta por cada coulomb. Se mide en volts, no en newtons.'],['R<sub>T</sub>','Resistencia externa total o equivalente (Ω).'],['r','Resistencia interna de la batería (Ω).'],['V<sub>T</sub>','Voltaje entre los terminales, disponible para el circuito externo (V).']])}${idea('Mientras la batería <strong>entrega corriente</strong>, la caída interna Ir hace que V<sub>T</sub> sea menor que ε, si r &gt; 0.')}<p>Con ε y r fijas, una corriente mayor produce una caída interna Ir mayor. Parte de la energía se transforma en calor dentro de la batería; no desaparece.</p><div class="compare"><div><h3>Fem ε</h3><p>Lo que aporta la fuente por cada unidad de carga.</p></div><div><h3>Voltaje terminal V<sub>T</sub></h3><p>Lo disponible entre sus terminales al alimentar el circuito.</p></div></div>${example('Una pila puede mostrar un voltaje casi normal sin carga, pero al alimentar un aparato ese voltaje baja. Su resistencia interna influye en esa caída.')}<details><summary>¿Cuándo puedo usar V<sub>T</sub> ≈ ε?</summary><p>Si la corriente es casi cero o la resistencia interna es despreciable. La expresión V<sub>T</sub> = ε − Ir de esta página corresponde a una batería que suministra corriente; durante la recarga cambian el sentido y la relación de signos.</p></details>`,
 questions:[q('¿Qué representa r en el modelo de una batería real?',['Su carga total.','La resistencia externa.','La resistencia interna.'],2,'r describe la oposición al paso de corriente dentro de la propia batería.'),q('¿Por qué Vₜ puede ser menor que ε cuando la batería entrega corriente?',['Porque hay una caída Ir en la resistencia interna.','Porque la corriente desaparece en la pila.','Porque ε se mide en amperes.'],0,'Parte de la energía por unidad de carga se transforma dentro de la batería.')]
 },
 {slug:'capacitores',key:'capacitores',title:'Separar cargas, guardar energía',heading:'Capacitores o condensadores',intro:'Un capacitor almacena carga separada y energía eléctrica. Su forma básica tiene dos placas conductoras con un aislante entre ellas.',
 body:`<p>Describimos esas cargas como <strong>+Q y −Q</strong>: tienen igual magnitud y signos opuestos. La energía queda almacenada en el campo eléctrico entre las placas.</p><div data-lab="capacitores"></div>${idea('«Carga almacenada Q» significa la magnitud de la carga de <strong>una placa</strong>. El capacitor ideal completo tiene carga neta cero: +Q + (−Q) = 0.')}<p><strong>Cargar</strong> es separar cargas mediante la fuente. <strong>Descargar</strong> es permitir que circulen por un camino externo y disminuya esa separación. Los electrones no atraviesan el aislante ideal entre las placas.</p>${example('En el flash de una cámara, un capacitor guarda energía y puede entregarla en un intervalo corto para producir el destello.')}<h2>Conectar varios capacitores</h2><div data-lab="asociaciones"></div><p>La <strong>capacitancia equivalente</strong> es la de un único capacitor que, visto desde los dos terminales del conjunto, almacena la misma Q total para el mismo voltaje aplicado.</p>`,
 questions:[q('Un capacitor ideal cargado tiene…',['Dos placas con cargas positivas.','Una placa +Q y otra −Q, de igual magnitud.','Una sola placa con carga.'],1,'Las cargas se separan: la suma total de ambas es cero.'),q('¿Qué comparten dos capacitores conectados en paralelo?',['El mismo voltaje entre sus terminales.','Siempre la misma carga aunque sus capacitancias difieran.','Una única placa conductora.'],0,'Cada capacitor está conectado entre los mismos dos nodos, por eso tiene el mismo voltaje.')]
 },
 {slug:'capacitancia',key:'capacitancia',title:'Cuánta carga por cada volt',heading:'La capacitancia es una propiedad',intro:'El capacitor es el objeto. La capacitancia indica cuánta carga puede separar por cada unidad de diferencia de potencial.',
 body:`${F('C=\\frac{Q}{V}\\qquad Q=CV','C = Q/V · Q = CV')}${terms([['C','Capacitancia, en faradios (F).'],['Q','Magnitud de la carga de una placa, en coulombs (C).'],['V','Diferencia de potencial entre las placas, en volts (V).']])}<p>Un faradio equivale a un coulomb por volt: <strong>1 F = 1 C/V</strong>. La letra C puede ser la variable capacitancia o el símbolo de la unidad coulomb: el contexto lo distingue.</p><div data-lab="capacitancia"></div>${idea('<strong>A igual voltaje, mayor capacitancia significa mayor carga almacenada.</strong>')}${example('Dos capacitores pueden conectarse a la misma batería y almacenar distintas cantidades de carga. El de mayor capacitancia separa más carga con ese mismo voltaje.')}`,
 questions:[q('¿Cuál es la unidad de capacitancia?',['Volt (V).','Coulomb (C).','Faradio (F).'],2,'El faradio expresa cuántos coulombs se almacenan por cada volt.'),q('Dos capacitores tienen el mismo voltaje. El que tiene mayor C…',['Almacena más carga en cada placa.','Debe almacenar menos carga.','Siempre tiene el mismo Q.'],0,'Q = CV. Si V es igual, una C mayor permite una Q mayor.')]
 },
 {slug:'placas-paralelas',key:'placas',title:'La forma también importa',heading:'Área, separación y material',intro:'En un capacitor de placas paralelas, la geometría y el aislante determinan la capacitancia.',
 body:`${F('C=\\frac{\\varepsilon A}{d}','C = εA/d')}${terms([['C','Capacitancia (F).'],['ε','Permitividad del material entre las placas (F/m). Aquí ε no es la fem de una batería.'],['A','Área de las superficies enfrentadas de las placas (m²).'],['d','Separación entre las placas (m).']])}<div data-lab="placas"></div><div class="compare"><div><h3>Más área</h3><p>Aumenta C. Menos área reduce C.</p></div><div><h3>Más separación</h3><p>Disminuye C. Acercar las placas aumenta C.</p></div></div><p>En cada comparación mantenemos las demás variables iguales. Cambiar el material puede cambiar ε y, por eso, C.</p>${idea('El área y la permitividad están <strong>arriba</strong>: aumentarlas aumenta C. La distancia está <strong>abajo</strong>: aumentarla disminuye C.')}<p class="small">Modelo ideal: placas grandes frente a su separación, material uniforme que llena el espacio y efectos de borde despreciables. Las placas no se tocan.</p>${example('En algunos sensores capacitivos, acercar una pieza cambia la capacitancia. El circuito detecta ese cambio para saber si hay un objeto cerca.')}`,
 questions:[q('Si aumenta el área A y lo demás permanece igual, ¿qué ocurre con C?',['Disminuye.','Aumenta.','No cambia.'],1,'Hay más superficie enfrentada. En C = εA/d, C es proporcional a A.'),q('Si separas más las placas, manteniendo A y ε iguales…',['C aumenta.','C siempre vale cero.','C disminuye.'],2,'La separación d está en el denominador: una d mayor reduce C.')]
 },
 {slug:'dielectricos',key:'dielectricos',title:'El material entre las placas',heading:'Dieléctricos y permitividad',intro:'Un dieléctrico es un aislante. Sus cargas ligadas pueden desplazarse un poco u orientarse sin circular libremente de una placa a la otra.',
 body:`<p>Esta pequeña reorganización se llama <strong>polarización</strong>. Permite almacenar más carga para el mismo voltaje que con vacío entre las placas.</p><div data-lab="dielectricos"></div>${F('\\varepsilon=\\varepsilon_0\\varepsilon_r=\\varepsilon_0K','ε = ε₀εᵣ = ε₀K')}${F('\\varepsilon_0\\approx 8.85\\times10^{-12}\\;\\mathrm{F/m}','ε₀ ≈ 8.85 × 10<sup>−12</sup> F/m')}${terms([['ε','Permitividad del material, en F/m.'],['ε₀','Permitividad del vacío, referencia para comparar.'],['εᵣ y K','Permitividad relativa o constante dieléctrica. Son la misma razón ε/ε₀ y no tienen unidades.']])}${idea('Vacío: <strong>K = 1</strong>. Aire: <strong>K ≈ 1</strong>. Con la misma geometría, un K mayor produce una capacitancia mayor.')}<h2>Materiales diferentes, valores diferentes</h2><p>No necesitas memorizar esta tabla. Úsala para comparar órdenes de magnitud.</p><div class="table-scroll"><table><thead><tr><th>Material</th><th>K aproximado</th></tr></thead><tbody><tr><td>Vacío</td><td>1 (exacto)</td></tr><tr><td>Aire</td><td>1</td></tr><tr><td>Papel parafinado</td><td>2</td></tr><tr><td>Teflón</td><td>2.1</td></tr><tr><td>Plástico (según el tipo)</td><td>Alrededor de 3</td></tr><tr><td>Aceite (según el tipo)</td><td>2.5–4</td></tr><tr><td>Mica</td><td>5–7</td></tr><tr><td>Vidrio</td><td>4–8</td></tr><tr><td>Agua</td><td>Alrededor de 80</td></tr></tbody></table></div><p class="small">Valores orientativos: dependen de la composición, temperatura y frecuencia. Un K alto no garantiza un buen aislante: el agua con sales conduce y no se usa como sustituto práctico del aislante de este modelo.</p>${example('Muchos capacitores llevan plástico o cerámica como aislante entre conductores. El material participa en su capacitancia; no sirve solamente para mantener las placas separadas.')}`,
 questions:[q('¿Qué representa K?',['Una corriente medida en amperes.','La permitividad relativa, sin unidades.','La carga total de la batería.'],1,'K = ε/ε₀ compara el material con el vacío. Las unidades se cancelan.'),q('¿Qué hace un dieléctrico ideal entre las placas?',['Conecta las placas como un cable.','Hace desaparecer las cargas.','Se polariza y modifica la capacitancia.'],2,'Sus cargas ligadas se reorganizan. No deja pasar libremente corriente entre las placas.')]
 },
 {slug:'repaso',key:'repaso',title:'Explícalo con tus palabras',heading:'Ya puedes conectar las ideas',intro:'Mira cada fórmula y cuenta qué representa. Después comprueba las conexiones en el reto final.',
 body:`<div class="recall-grid">${[
 ['P = I²R','Calentamiento','La corriente transfiere energía al material resistivo. A I fija, más R significa más potencia térmica.'],
 ['Σ I entra = Σ I sale','Un nodo','La carga se conserva: la corriente se reparte sin crearse ni desaparecer.'],
 ['Σ ΔV = 0','Una malla','Las subidas y caídas de potencial se equilibran en una vuelta completa.'],
 ['Vₜ = ε − Ir','Una batería real','Mientras entrega corriente, parte del aporte por coulomb se transforma dentro de la batería.'],
 ['C = Q/V','Capacitancia','Carga de una placa por cada volt entre las placas. A V fijo, más C permite más Q.'],
 ['C = εA/d','La geometría','Mayor área o permitividad: más C. Mayor separación: menos C.'],
 ['ε = ε₀K','El material','K compara la permitividad del material con la del vacío y no tiene unidades.']
 ].map(([f,t,a])=>`<details><summary><strong>${f}</strong><span>${t}</span></summary><p>${a}</p></details>`).join('')}</div>${idea('Para leer una fórmula, pregunta: <strong>¿qué fenómeno describe?, ¿qué significa cada letra?, ¿qué mantengo fijo y qué cambia?</strong>')}`,
 questions:[q('Una pregunta menciona una unión y corrientes que se reparten. ¿Qué relación corresponde?',['Primera ley → nodo → conservación de carga.','Segunda ley → nodo → conservación de energía.','Capacitancia → resistencia interna.'],0,'Las corrientes en una unión se describen con la ley de nodos.'),q('Si una batería entrega más corriente con ε y r fijas, ¿qué sucede?',['Ir disminuye y Vₜ aumenta.','Ir aumenta y Vₜ disminuye.','La fem se convierte en resistencia.'],1,'Vₜ = ε − Ir: una caída interna mayor deja menos voltaje en los terminales.'),q('En un capacitor ideal con C fija, aumentar V hace que…',['Q aumente en la misma proporción.','C aumente automáticamente.','Q se vuelva cero.'],0,'Q = CV. Aumenta la carga separada; la capacitancia no cambia por cargarlo.'),q('Con la misma geometría, sustituyes vacío por un dieléctrico con K > 1. ¿Qué cambia?',['La capacitancia disminuye.','K adquiere unidades de faradio.','La capacitancia aumenta.'],2,'C = ε₀KA/d. El material aumenta la permitividad y la capacitancia.')]
 }
];

expandLessons(pages,F);
