// Desarrollo narrativo: conecta los conceptos, los diagramas y los ejemplos resueltos.
export function expandLessons(pages,F){
 const lesson={
  joule:{
   intro:'Imagina que enciendes una tostadora. La resistencia se calienta, pero ¿de dónde sale ese calor? Empezaremos por esa pregunta y seguiremos la energía y la carga a través del circuito.',
   lead:'<p>Para entenderlo, separa dos ideas. La <strong>corriente</strong> nos dice cuánta carga pasa por un lugar cada segundo. La <strong>energía</strong> es lo que esa carga puede transferir al material. La batería mantiene el movimiento de carga y aporta la energía que después se transforma.</p>',
   guide:'<p>Ahora observa el material por dentro. Los puntos azules representan electrones y los círculos grandes representan la estructura del conductor. Enciende el modelo y cambia primero la corriente, dejando igual la resistencia. Después vuelve a la corriente menor y cambia solamente la resistencia.</p>',
   after:'<p>Lo que acabas de observar se llama efecto Joule. Para describir <em>qué tan rápido</em> se transforma la energía usamos la potencia P. No es la temperatura del material: es la cantidad de energía que se transforma cada segundo. La siguiente fórmula relaciona esa rapidez con la corriente y la resistencia.</p>',
   worked:`<h3>Veámoslo con una resistencia pequeña</h3><p>Supón que una corriente de <strong>2 A</strong> atraviesa una resistencia de <strong>3 Ω</strong>. En P = I²R sustituimos I por 2 y R por 3. Primero elevamos la corriente al cuadrado y después multiplicamos por la resistencia.</p>${F('P=(2)^2(3)=4(3)=12\\;\\mathrm{W}','P = 2² × 3 = 4 × 3 = 12 W')}<p><strong>12 W significa 12 joules de energía transformados cada segundo.</strong> Si se mantiene así durante 5 segundos, transforma 60 J. Eso no significa que su temperatura aumente 12 grados: la temperatura también depende del material y de cuánto calor cede al ambiente.</p><p>Ahora conserva la misma resistencia y duplica la corriente a 4 A. La potencia será 4² × 3 = 48 W: cuatro veces la anterior. Por eso una corriente mayor puede aumentar mucho el calentamiento.</p>`,
   ending:'Ya sabemos qué le ocurre a la energía cuando la corriente atraviesa una resistencia. Pero un circuito puede tener varios caminos. En la siguiente página veremos cómo se reparte la corriente al llegar a una unión.'
  },
  nodos:{
   intro:'En la página anterior seguimos la corriente por un material. Ahora llegamos a una unión: la carga puede continuar por distintas ramas. ¿Cómo se relaciona lo que llega con lo que sale?',
   lead:'<p>A esa unión la llamamos <strong>nodo</strong>. Piensa en una entrada que se divide en varios caminos: lo que llega puede repartirse, pero no se multiplica por el hecho de encontrar una bifurcación. En un circuito estable tampoco se va acumulando carga indefinidamente en la unión.</p><p>Por eso contamos todas las corrientes de entrada y las comparamos con todas las de salida. No exigimos que cada rama lleve lo mismo; exigimos que los <strong>totales</strong> coincidan.</p>',
   guide:'<p>En el dibujo hay dos entradas y dos salidas. Cambia el reparto entre I₃ e I₄. Fíjate en que cambia el tamaño de cada parte de la barra de salida, pero no cambia su longitud total.</p>',
   after:'<p>Esa igualdad entre totales es la primera ley de Kirchhoff. El símbolo Σ permite escribir «suma de todas» sin tener que nombrar cada rama por separado.</p>',
   worked:`<h3>Una unión con 10 A en total</h3><p>Imagina que entran <strong>6 A</strong> por una rama y <strong>4 A</strong> por otra. En total llegan 10 A. Si por una salida pasan 3 A, por la otra deben pasar 7 A.</p>${F('6+4=3+7=10\\;\\mathrm{A}','6 + 4 = 3 + 7 = 10 A')}<p>Podemos leerlo así: «cada segundo llegan 10 coulombs de carga y salen 10 coulombs». Si una salida pasa de 3 A a 5 A y el total de entrada se mantiene igual, la otra debe pasar de 7 A a 5 A.</p><p><strong>No tiene que ser mitad y mitad.</strong> El reparto depende de las ramas conectadas; la ley solo nos exige que la carga se conserve.</p>`,
   ending:'La primera ley responde cuánto entra y cuánto sale de una unión. Ahora cambiaremos la pregunta: al dar una vuelta completa por un circuito, ¿qué ocurre con la energía por unidad de carga? Esa es la idea de la segunda ley.'
  },
  mallas:{
   intro:'Ya vimos que la carga se conserva en una unión. Ahora vamos a recorrer un circuito completo y seguir los cambios de potencial, es decir, los cambios de energía por unidad de carga.',
   lead:'<p>Empieza en el terminal negativo de la batería y recorre el circuito hasta regresar al mismo punto. Ese recorrido es una <strong>trayectoria cerrada</strong>. En el circuito sencillo del dibujo forma una malla.</p><p>Al atravesar la fuente de − a + hay una subida de potencial. Después, al seguir la corriente por las resistencias, hay caídas. Puedes imaginar un recorrido que sube y luego baja: para terminar a la misma altura, las subidas y las bajadas deben compensarse. Aquí seguimos potencial eléctrico, no altura real.</p>',
   guide:'<p>Pulsa «Avanzar en la malla» con calma. En cada paso, observa qué elemento se destaca y si la barra de potencial sube, baja o permanece igual. Al completar la vuelta debes recuperar el valor inicial.</p>',
   after:'<p>Ahora podemos escribir lo que observaste. ΔV significa un cambio de voltaje; la suma lleva signos porque algunas partes del recorrido suben el potencial y otras lo bajan.</p>',
   worked:`<h3>Una subida de 12 V y dos caídas</h3><p>Supón una batería ideal de <strong>12 V</strong> y dos resistencias en serie de <strong>2 Ω</strong> y <strong>4 Ω</strong>. Circula la misma corriente de 2 A por ambas. En la primera, la caída IR₁ es 2 × 2 = 4 V. En la segunda, IR₂ es 2 × 4 = 8 V.</p>${F('+12-4-8=0\\;\\mathrm{V}','+12 − 4 − 8 = 0 V')}<p>La batería aporta 12 J por cada coulomb. La primera resistencia transforma 4 J por coulomb y la segunda transforma 8 J por coulomb. <strong>Se repartió la energía aportada; no desapareció la carga.</strong> La corriente sigue siendo 2 A en las dos resistencias.</p><p>Por eso la segunda ley habla de <strong>conservación de energía</strong>, mientras que la primera habla de conservación de carga. No son dos maneras de decir lo mismo: miran aspectos diferentes del circuito.</p>`,
   ending:'Hasta aquí tratamos a la batería como una fuente ideal. En una batería real también se transforma energía dentro de ella. Vamos a incorporar esa parte al mismo razonamiento de subidas y caídas.'
  },
  bateria:{
   intro:'En la malla anterior toda la caída de voltaje estaba en las resistencias externas. Ahora vamos a incluir una resistencia que no vemos desde fuera: la resistencia interna de la batería.',
   lead:'<p>Una batería produce una <strong>fem ε</strong>: un aporte de energía por cada unidad de carga. Aunque su nombre sea «fuerza electromotriz», se mide en volts. Por ejemplo, una fem de 12 V significa que la fuente aporta 12 joules por coulomb.</p><p>Pero la carga también atraviesa el interior de la batería, donde existe una resistencia r. Allí se transforma parte de la energía. El circuito externo recibe lo que queda, y eso se refleja en el <strong>voltaje terminal V<sub>T</sub></strong>.</p>',
   guide:'<p>Empieza con el circuito desconectado: sin corriente, la caída interna es cero. Después conecta una resistencia externa. Observa cómo el aporte de la fuente se divide entre la caída interna y el voltaje disponible en los terminales.</p>',
   after:'<p>Para encontrar la corriente sumamos las dos resistencias que debe atravesar: R<sub>T</sub>, la externa, y r, la interna. Para encontrar el voltaje terminal restamos a ε la caída interna Ir. Las dos fórmulas describen el mismo circuito desde dos preguntas distintas.</p>',
   worked:`<h3>¿Qué recibe realmente el aparato?</h3><p>Considera una batería de <strong>ε = 12 V</strong>, con <strong>r = 1 Ω</strong>, conectada a una resistencia externa de <strong>R<sub>T</sub> = 5 Ω</strong>. Primero encontramos la corriente usando los 6 Ω de resistencia total.</p>${F('I=\\frac{12}{5+1}=2\\;\\mathrm{A}','I = 12/(5 + 1) = 2 A')}<p>Con esa corriente, la caída dentro de la batería es Ir = 2 × 1 = 2 V. Por tanto, entre los terminales quedan 10 V.</p>${F('V_T=12-2=10\\;\\mathrm{V}','Vₜ = 12 − 2 = 10 V')}<p>Leído como energía: la fuente aporta 12 J por coulomb, 2 J por coulomb se transforman dentro de la batería y 10 J por coulomb quedan para el exterior. Es la misma conservación de energía que usamos en la malla.</p><p>Si reducimos R<sub>T</sub> a 2 Ω, manteniendo ε y r, circularán 4 A y la caída interna será 4 V. El voltaje terminal bajará a 8 V. Así se entiende por qué un aparato que exige más corriente puede hacer caer más el voltaje de la batería.</p>`,
   ending:'Ya distinguimos la energía que aporta la fuente de la que llega a otro elemento. A continuación veremos un elemento que puede guardar energía mediante una separación de cargas: el capacitor.'
  },
  capacitores:{
   intro:'Una resistencia transforma energía en calor. Un capacitor puede almacenarla temporalmente en un campo eléctrico. Para entender cómo lo hace, primero observa qué ocurre en sus dos placas.',
   lead:'<p>Imagina dos placas metálicas enfrentadas, separadas por un aislante. Antes de cargarlas, cada una tiene equilibradas sus cargas positivas y negativas. Al conectarlas a una batería, esta retira electrones de una placa y aporta electrones a la otra.</p><p>La placa que pierde electrones queda positiva; la que los recibe queda negativa. El aislante evita que los electrones crucen directamente de una placa a la otra. Así puede mantenerse la separación de cargas.</p>',
   guide:'<p>Pulsa «Cargar» y observa los signos. Luego pulsa «Desconectar»: quitar la batería no da por sí solo un camino para que la carga regrese. Finalmente pulsa «Descargar», que representa abrir un camino externo a través de una resistencia.</p>',
   after:'<p>La diferencia entre desconectar y descargar es importante. En el modelo ideal, dejar el capacitor aislado conserva su carga. En cambio, conectarlo a un camino de descarga permite que disminuya la separación de cargas y que la energía se transfiera a ese camino.</p>',
   worked:`<h3>¿Cómo puede estar cargado y sumar cero?</h3><p>Supón que una placa tiene <strong>+6 μC</strong> y la otra <strong>−6 μC</strong>. El símbolo μC significa microcoulomb: una millonésima de coulomb.</p>${F('(+6)+(-6)=0\\;\\mu\\mathrm{C}','(+6) + (−6) = 0 μC')}<p>La carga neta del conjunto es cero, pero las cargas están <strong>separadas</strong>. Por eso existe un campo y puede haber energía almacenada. Cuando decimos «el capacitor almacena Q = 6 μC», usamos la magnitud de la carga de una placa, no la suma de las dos ni 12 μC.</p><p>Durante la descarga, las magnitudes van disminuyendo: por ejemplo, pueden pasar de +6 y −6 a +3 y −3 μC, hasta llegar idealmente a cero. No se destruye carga; se redistribuye por el circuito externo.</p>`,
   ending:'Ya entendemos qué significa cargar un capacitor. Falta responder cuánto puede almacenar para un voltaje determinado. Para eso necesitamos una propiedad llamada capacitancia.'
  },
  capacitancia:{
   intro:'En la página anterior separamos cargas entre dos placas. Ahora vamos a comparar capacitores: si los conectamos al mismo voltaje, ¿todos separan la misma cantidad de carga?',
   lead:'<p>No necesariamente. El <strong>capacitor</strong> es el dispositivo; su <strong>capacitancia C</strong> indica cuánta carga puede separar por cada volt aplicado. Un capacitor de mayor capacitancia puede almacenar más carga que otro al mismo voltaje.</p><p>La fórmula C = Q/V expresa justamente «carga por volt». También podemos escribir Q = CV si queremos saber la carga que corresponde a un voltaje concreto. No son dos leyes distintas: es la misma relación despejada de otra manera.</p>',
   guide:'<p>Compara ahora los dos capacitores del dibujo. Los conectamos al mismo voltaje, pero el de la derecha tiene el doble de capacitancia. Cambia el voltaje y observa la cantidad de signos de cada lado: el de 2C mantiene el doble de carga que el de C.</p>',
   after:'<p>Fíjate en qué cambió y qué no. Al subir el voltaje aumentaron las cargas de las placas. Sin embargo, las etiquetas C y 2C permanecieron iguales. Para estos capacitores ideales, la geometría y el material no cambiaron: cargar más no significa cambiar su capacitancia.</p>',
   worked:`<h3>Un capacitor de 2 μF conectado a 3 V</h3><p>Los capacitores comunes suelen tener capacitancias mucho menores que un faradio. Aquí usaremos <strong>2 microfaradios, o 2 μF</strong>. Eso significa que puede separar 2 μC por cada volt. Si aplicamos 3 V, obtenemos:</p>${F('Q=CV=(2\\;\\mu\\mathrm{F})(3\\;\\mathrm{V})=6\\;\\mu\\mathrm{C}','Q = CV = (2 μF)(3 V) = 6 μC')}<p>Por tanto, una placa queda con +6 μC y la otra con −6 μC, como en la página anterior. Si dividimos esos 6 μC entre los 3 V, recuperamos C = 2 μF.</p><p>Ahora cambia <strong>solo el voltaje</strong> a 6 V: la carga pasa a 12 μC, pero C sigue siendo 2 μF. En cambio, si usas un capacitor de 4 μF a los mismos 3 V del inicio, también almacena 12 μC. En un caso cambió V; en el otro cambió C.</p>`,
   ending:'La capacitancia nos dice cuánta carga corresponde a cada volt. Ahora veremos de dónde sale esa propiedad: depende de la forma de las placas, de su separación y del material entre ellas.'
  },
  placas:{
   intro:'Acabamos de comparar capacitores de distinta capacitancia. Ahora vamos a entender cómo se consigue una C mayor o menor cambiando físicamente las placas.',
   lead:'<p>Para comparar con claridad, imagina placas paralelas y cambia una sola cosa cada vez. Si aumentas la superficie enfrentada, hay más área disponible para separar carga. Si alejas las placas, hace falta más voltaje para mantener la misma carga; por eso disminuye la carga almacenada por volt.</p><p>La fórmula reúne estas dos ideas. El área A multiplica en el numerador y la distancia d divide en el denominador. La permitividad ε añade el efecto del material situado entre las placas.</p>',
   guide:'<p>Comienza en la referencia inicial. Haz el área mediana sin mover la separación ni cambiar el material. Después restablece y duplica únicamente la separación. Compara ambos resultados antes de combinar varios cambios.</p>',
   after:'<p>El número del modelo compara C con su valor inicial. «2 × C inicial» significa el doble, mientras que «0.5 × C inicial» significa la mitad. No necesitas calcular una capacitancia en faradios para reconocer esas relaciones.</p>',
   worked:`<h3>Partamos de un capacitor de 4 μF</h3><p>Conserva el mismo material y la misma separación. Si duplicas el área, la capacitancia se duplica:</p>${F('C_{\\mathrm{nueva}}=2(4)=8\\;\\mu\\mathrm{F}','C nueva = 2 × 4 = 8 μF')}<p>Vuelve ahora al capacitor original de 4 μF. Mantén el área y el material, pero duplica la separación. Como d está en el denominador, C se reduce a la mitad:</p>${F('C_{\\mathrm{nueva}}=\\frac{4}{2}=2\\;\\mu\\mathrm{F}','C nueva = 4/2 = 2 μF')}<p>¿Y si duplicas a la vez el área y la separación? Los efectos se compensan: multiplicar arriba por 2 y abajo por 2 conserva la razón A/d. La capacitancia vuelve a ser 4 μF. Por eso es importante decir qué variable cambió y cuáles permanecieron iguales.</p>`,
   ending:'Nos queda interpretar ε, el efecto del material. En la siguiente página veremos cómo un aislante puede aumentar la capacitancia sin cambiar ni el área ni la separación.'
  },
  dielectricos:{
   intro:'Hasta ahora cambiamos el tamaño y la separación de las placas. Dejemos ambas cosas fijas y cambiemos únicamente el material que hay entre ellas.',
   lead:'<p>Un <strong>dieléctrico</strong> es un material aislante: sus cargas no circulan libremente como en un cable. Sin embargo, el campo de las placas puede desplazar un poco sus cargas ligadas u orientar sus moléculas. El material sigue siendo aislante, pero responde al campo.</p><p>Esa respuesta modifica la relación entre carga y voltaje. Con una batería que mantiene el mismo V, puede quedar más carga en las placas. Como C = Q/V, almacenar más Q al mismo V significa tener una capacitancia mayor.</p>',
   guide:'<p>Introduce el dieléctrico en el dibujo. Los signos pequeños representan cargas ligadas del material, no electrones cruzando el aislante. La cara negativa de cada pequeño conjunto se orienta hacia la placa positiva. Observa también las barras: el voltaje se mantiene fijo y aumentan C y Q.</p>',
   after:'<p>Para expresar cuánto influye el material usamos su permitividad ε. La comparamos con la del vacío, ε₀. La razón entre ambas se llama permitividad relativa εᵣ o constante dieléctrica K: aquí esos dos símbolos representan lo mismo.</p>',
   worked:`<h3>¿Qué quiere decir K = 2?</h3><p>Significa que la permitividad del material es dos veces la del vacío. No significa «dos faradios»: K es una comparación y <strong>no tiene unidades</strong>.</p>${F('\\varepsilon=2\\varepsilon_0','ε = 2ε₀')}<p>Supón que un capacitor tiene <strong>2 μF con vacío</strong> entre sus placas. Si llenamos ese espacio con un dieléctrico de K = 2, manteniendo la geometría, su capacitancia pasa a 4 μF.</p><p>Si además sigue conectado a una batería de 3 V, la carga de cada placa pasa de 6 μC a 12 μC. La batería aporta esa carga adicional. Así conectamos las dos fórmulas: el material aumenta C y, como Q = CV con V fijo, aumenta Q.</p><p>Si el capacitor estuviera desconectado y aislado, no habría una batería aportando carga: Q se conservaría y disminuiría V. Por eso el dibujo especifica que está conectado a una fuente de voltaje fijo.</p>`,
   ending:'Ya puedes seguir toda la explicación: el material determina ε, ε influye en C y C relaciona la carga con el voltaje. En el repaso final uniremos estas ideas con la corriente, la batería y las leyes de Kirchhoff.'
  },
  repaso:{
   intro:'Ahora vamos a reconstruir el recorrido, en lugar de estudiar las fórmulas como piezas separadas. Primero piensa en la batería y el circuito; después, en lo que ocurre al cargar un capacitor.',
   lead:`<p>La <strong>batería</strong> aporta energía por unidad de carga. Cuando hay corriente, las <strong>resistencias</strong> transforman parte de esa energía en calor por efecto Joule. Si la corriente encuentra una unión, la primera ley de Kirchhoff indica cómo se relacionan las entradas y salidas. Si recorremos una vuelta completa, la segunda ley relaciona las subidas y caídas de potencial.</p><h3>Una misma situación, varias ideas</h3><p>Retoma la batería de 12 V con resistencia interna de 1 Ω y resistencia externa de 5 Ω. La corriente es 2 A. Dentro de la batería caen 2 V y fuera caen 10 V: 12 − 2 − 10 = 0. Esa es la ley de mallas. La resistencia interna transforma 2² × 1 = 4 W en calor: ese es el efecto Joule. Son dos formas de describir aspectos de la misma situación.</p><p>Ahora piensa en un capacitor de 2 μF conectado a 3 V. Al terminar de cargarse tiene 6 μC en cada placa, con signos opuestos. Si duplicamos su capacitancia manteniendo 3 V, almacena 12 μC. Podemos aumentar C cambiando el área, la separación o el dieléctrico. Así las fórmulas cuentan una historia que podemos explicar.</p><p>Antes de abrir cada tarjeta, intenta decir en voz alta qué representa la fórmula. Luego compárala con la explicación y vuelve al ejemplo si algo no queda claro.</p>`,
   ending:'Al responder el reto, busca primero la situación física: ¿una unión, una vuelta, una batería o unas placas? Después elige la relación que describe esa situación y explica por qué.'
  }
 };
 for(const p of pages){const e=lesson[p.key];p.intro=e.intro;
  p.body=p.key==='joule'?p.body.replace('<h2>Efecto Joule</h2>','<h2>Efecto Joule</h2>'+e.lead):e.lead+p.body;
  if(e.guide){const marker=`<div data-lab="${p.key}"></div>`;p.body=p.body.replace(marker,e.guide+marker+e.after);}
  if(e.worked){const pos=p.body.indexOf(p.key==='dielectricos'?'<h2>Materiales diferentes':'<div class="everyday">');p.body=pos<0?p.body+e.worked:p.body.slice(0,pos)+`<section class="worked-example">${e.worked}</section>`+p.body.slice(pos);}
  if(p.key==='capacitores')p.body=p.body.replace('<h2>Conectar varios capacitores</h2>','<h2>Conectar varios capacitores</h2><p>Podemos usar más de un capacitor. En paralelo, cada uno se conecta a los mismos dos puntos y recibe el mismo voltaje. En serie, quedan uno después del otro y el voltaje total se reparte entre ellos. Observa cómo cambian los cables al alternar las dos conexiones.</p>');
  p.body+=`<p class="lesson-bridge">${e.ending}</p>`;
 }
}
