import {heating,battery,capacitance,charge,equivalent,junction,loop} from './modelos.mjs';
const svg=(label,body)=>`<svg viewBox="0 0 600 330" role="img" aria-label="${label}"><defs><marker id="arrow-${label.split(' ')[0]}" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 6 3 0 6" fill="currentColor"/></marker></defs>${body}</svg>`;
const line=(x1,y1,x2,y2,cls='wire')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${cls}"/>`;
const text=(x,y,t,cls='')=>`<text x="${x}" y="${y}" class="${cls}">${t}</text>`;
const label=(title,control)=>`<label>${title}${control}</label>`;
const select=(id,options)=>`<select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select>`;
const buttons=(id,labels)=>`<div class="segmented" id="${id}">${labels.map(([v,t])=>`<button type="button" data-value="${v}" aria-pressed="false">${t}</button>`).join('')}</div>`;
const lab=(title,body,controls,note)=>`<section class="lab"><div class="lab-head"><h3>${title}</h3><span class="lab-dot" aria-hidden="true">✦</span></div><div class="lab-visual">${body}</div><div class="lab-controls">${controls}</div><p class="lab-result" role="status"></p><p class="small lab-caption">${note}</p></section>`;
const meter=(id,title)=>`<div class="meter"><span>${title}</span><div><i id="${id}"></i></div></div>`;
export function markup(key){
 if(key==='joule')return lab('Enciende y observa',svg('Conductor con electrones y átomos',`<rect id="conductor" x="45" y="70" width="510" height="175" rx="35"/>${Array.from({length:15},(_,i)=>`<g class="atom" style="--delay:${i*.09}s"><circle cx="${90+(i%5)*105}" cy="${100+Math.floor(i/5)*55}" r="13"/>${text(90+(i%5)*105,106+Math.floor(i/5)*55,'+')}</g>`).join('')}${Array.from({length:8},(_,i)=>`<g class="electron" style="--delay:${i*-.4}s"><circle cx="${100+i*54}" cy="${i%2?180:130}" r="7"/></g>`).join('')}${text(300,35,'Corriente convencional →')}${text(300,295,'Electrones: desplazamiento medio ←')}`),buttons('power-switch',[['off','Apagar'],['on','Encender']])+label('Corriente',select('joule-i',[[1,'Menor'],[2,'Mayor']]))+label('Resistencia',select('joule-r',[[1,'Menor'],[2,'Mayor']]))+meter('heat-bar','Calentamiento por segundo')+`<button type="button" id="joule-pause" aria-pressed="false">Pausar movimiento</button>`,'Círculos grandes: estructura del material. Puntos azules: electrones. Movimiento y calentamiento esquemáticos; no representan velocidades ni temperaturas reales. Al variar un control, el otro se mantiene fijo.') ;
 if(key==='nodos')return lab('Sigue las flechas',svg('Nodo con dos entradas y dos salidas',`<path d="M55 80 300 165M55 250 300 165" class="wire entering"/><path d="M300 165 545 80M300 165 545 250" class="wire leaving"/><path d="m175 113 24 16-30 2m6 80 24-16-30-2" class="arrow-in"/><path d="m426 111 24 2-19 18m-5 75 24 11-20 6" class="arrow-out"/><circle cx="300" cy="165" r="20" class="junction"/>${text(80,55,'I₁ entra')}${text(80,285,'I₂ entra')}${text(520,55,'I₃ sale')}${text(520,285,'I₄ sale')}${text(300,215,'Nodo')}`),buttons('node-share',[['3','Más hacia I₄'],['5','Reparto igual'],['7','Más hacia I₃']])+`<div class="flow-balance"><div><strong>Entran</strong><div class="stack"><i style="width:60%">I₁</i><i style="width:40%">I₂</i></div></div><span>=</span><div><strong>Salen</strong><div class="stack output"><i id="out-a">I₃</i><i id="out-b">I₄</i></div></div></div>`,'Las barras representan corriente: la longitud total de entrada y de salida es igual. Cambiar el reparto corresponde a cambiar las ramas del circuito.');
 if(key==='mallas')return lab('Recorre la malla',svg('Malla con batería y dos resistencias',`<path d="M100 180V65H500V270H100V210" class="wire"/><g id="loop-source">${line(72,180,128,180)}${line(84,210,116,210)}${text(55,177,'+')}${text(55,222,'−')}${text(65,145,'ε')}</g><g id="loop-r1"><rect class="resistor" x="255" y="50" width="90" height="30"/>${text(300,36,'R₁')}</g><g id="loop-r2"><rect class="resistor" x="485" y="120" width="30" height="85"/>${text(555,165,'R₂')}</g><path d="M380 95h55l-12-8m12 8-12 8" class="wire"/>${text(300,170,'Recorrido horario')}${text(300,200,'I →')}`),`<div class="step-description"><h4 id="loop-title"></h4><p id="loop-copy"></p></div>${meter('potential-bar','Potencial respecto al inicio')}<div class="button-row"><button type="button" id="loop-reset">Volver al inicio</button><button type="button" id="loop-next" class="primary">Avanzar en la malla →</button></div>`,'La barra representa potencial, no cantidad de carga. En los cables ideales no hay caída de voltaje.');
 if(key==='bateria')return lab('Dentro y fuera de la batería',svg('Batería real y resistencia externa',`<rect x="55" y="40" width="300" height="250" rx="30" class="battery-case"/><path d="M100 180V90H500V255H100V210" class="wire"/>${line(73,180,127,180)}${line(85,210,115,210)}${text(65,170,'+')}${text(65,227,'−')}${text(100,145,'ε')}<rect x="205" y="76" width="75" height="28" class="resistor internal"/>${text(244,63,'r')}<rect x="485" y="135" width="30" height="75" class="resistor"/>${text(550,180,'Rₜ')}<circle cx="355" cy="90" r="6" class="terminal"/><circle cx="355" cy="255" r="6" class="terminal"/>${text(405,190,'Vₜ')}<path d="M385 90H445" stroke="white" stroke-width="10"/><path id="battery-switch" d="M385 90 445 60" class="wire"/>${text(215,320,'Batería real')}`),label('Resistencia interna r',select('battery-r',[[0,'Ideal: sin r'],[1,'Pequeña'],[3,'Mayor']]))+label('Circuito externo',select('battery-load',[['open','Desconectado'],[6,'Mayor Rₜ'],[2,'Menor Rₜ']]))+`<div class="battery-bars">${meter('emf-bar','Aporte de la fuente ε')}${meter('loss-bar','Caída interna Ir')}${meter('terminal-bar','Voltaje terminal Vₜ')}</div>`,'La fem se mantiene fija. Las barras comparten escala: Vₜ + Ir = ε. El modelo representa una batería que entrega corriente.');
 if(key==='capacitores')return lab('Carga y descarga',svg('Capacitor con placas y camino externo',`<path d="M220 80V55H70V280H530V55H380V80" class="wire"/><rect x="205" y="80" width="22" height="140" rx="5" class="positive-plate"/><rect x="373" y="80" width="22" height="140" rx="5" class="negative-plate"/><rect x="240" y="85" width="120" height="130" rx="10" class="insulator"/>${text(300,150,'Aislante')}${text(200,35,'+Q')}${text(405,35,'−Q')}<g id="stored-charges">${Array.from({length:6},(_,i)=>text(216,100+i*21,'+','positive-charge')+text(384,100+i*21,'−','negative-charge')).join('')}</g><rect x="238" y="259" width="125" height="43" rx="8" class="source-label"/>${text(300,286,'Fuente','path-label')}`),buttons('capacitor-state',[['charge','Cargar'],['isolate','Desconectar'],['discharge','Descargar']])+meter('charge-bar','Carga separada'),'Modelo ideal. Cargar y descargar requieren un camino externo; aquí se muestra el estado final de cada acción, con una transición visual.');
 if(key==='asociaciones')return lab('Dos formas de conectarlos',`<div id="association-diagram"></div>`,buttons('association-mode',[['series','En serie'],['parallel','En paralelo']])+`<p class="association-formula"></p>`,'Comparamos dos capacitores idénticos de capacitancia C, inicialmente descargados. Las líneas son cables y los pares de barras son capacitores.');
 if(key==='capacitancia')return lab('Mismo voltaje, distinta carga',`<div class="capacitor-comparison"><div><h4>Capacitancia C</h4><div class="charge-pair" id="charge-a"></div><p id="amount-a"></p></div><div><h4>Capacitancia 2C</h4><div class="charge-pair" id="charge-b"></div><p id="amount-b"></p></div></div>`,label('Voltaje igual en ambos',select('common-voltage',[[1,'Voltaje inicial'],[2,'El doble'],[3,'El triple']])),'Cada signo representa la misma cantidad de carga. Las capacitancias permanecen fijas durante toda la comparación.');
 if(key==='placas')return lab('Cambia una cosa y observa',svg('Placas paralelas con geometría variable',`<rect id="plate-material" x="250" y="90" width="100" height="150" rx="12" class="insulator"/><rect id="plate-left" x="230" y="90" width="15" height="150" rx="5" class="positive-plate"/><rect id="plate-right" x="355" y="90" width="15" height="150" rx="5" class="negative-plate"/>${text(300,35,'Placas enfrentadas')}<path id="distance-line" d="M245 265H355" class="wire"/>${text(300,295,'d')}${text(140,170,'Área A')}`),label('Área A',select('plate-area',[[1,'Pequeña'],[2,'Mediana'],[3,'Grande']]))+label('Separación d',select('plate-distance',[[1,'Cercanas'],[2,'Separación doble'],[3,'Separación triple']]))+label('Material',select('plate-k',[[1,'Vacío: K = 1'],[2,'Dieléctrico: K = 2'],[4,'Dieléctrico: K = 4']]))+`<div class="capacity-readout"><strong id="capacity-ratio"></strong><span>respecto a la referencia inicial</span></div><button type="button" id="plates-reset">Restablecer comparación</button>`,'Referencia: área pequeña, placas cercanas y vacío. El dibujo muestra relaciones; no está a escala. Cambiar el área mantiene fija la separación y viceversa.');
 if(key==='dielectricos')return lab('Introduce un aislante',svg('Dieléctrico polarizado entre placas',`<rect x="145" y="55" width="20" height="220" rx="6" class="positive-plate"/><rect x="435" y="55" width="20" height="220" rx="6" class="negative-plate"/>${text(155,36,'+Q')}${text(445,36,'−Q')}<g id="dielectric-block"><rect x="185" y="65" width="230" height="200" rx="15" class="insulator"/>${Array.from({length:9},(_,i)=>`<g>${line(220+i%3*70,105+Math.floor(i/3)*60,240+i%3*70,105+Math.floor(i/3)*60,'dipole')}${text(216+i%3*70,111+Math.floor(i/3)*60,'−','dipole-sign')}${text(244+i%3*70,111+Math.floor(i/3)*60,'+','dipole-sign')}</g>`).join('')}</g>${text(300,315,'Voltaje fijo: conectado a una batería')}`),buttons('dielectric-state',[['out','Sin dieléctrico'],['in','Introducir dieléctrico']])+meter('dielectric-c','Capacitancia')+meter('dielectric-q','Carga de cada placa'),'Al llenar el espacio con un dieléctrico de K = 2 y mantener V fijo, C y Q se duplican. Los signos pequeños son cargas ligadas dentro del aislante.');
 return '';
}
export function mountLabs(root){
 const $=s=>root.querySelector(s),key=root.dataset.lab,result=$('.lab-result');
 const set=(s,t)=>$(s).textContent=t;
 const bar=(s,p)=>$(s).style.width=`${p}%`;
 const pressed=(selector,value)=>$(selector).querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===String(value))));
 function onGroup(selector,callback){$(selector).addEventListener('click',e=>{const b=e.target.closest('button');if(b){pressed(selector,b.dataset.value);callback(b.dataset.value);}});}
 if(key==='joule'){
  let on=false;function update(){const i=+$('#joule-i').value,r=+$('#joule-r').value,p=on?heating(i,r):0;root.classList.toggle('running',on);$('#conductor').style.fill=`hsl(28 75% ${96-p*4}%)`;bar('#heat-bar',p/8*100);result.textContent=on?`Corriente ${i===1?'menor':'mayor'} y resistencia ${r===1?'menor':'mayor'}. Los electrones transfieren energía al material. Si solo aumentas I o solo aumentas R, sube P = I²R.`:'Sin corriente no hay calentamiento por efecto Joule. El material puede tener movimiento térmico aunque el circuito esté apagado.';}
  onGroup('#power-switch',v=>{on=v==='on';update();});$('#joule-i').onchange=$('#joule-r').onchange=update;pressed('#power-switch','off');$('#joule-pause').onclick=()=>{const paused=root.classList.toggle('paused');$('#joule-pause').setAttribute('aria-pressed',paused);$('#joule-pause').textContent=paused?'Reanudar movimiento':'Pausar movimiento';};update();
 }
 if(key==='nodos'){
  function update(v){const n=junction(+v);bar('#out-a',n.outA*10);bar('#out-b',n.outB*10);result.textContent='I₁ + I₂ = I₃ + I₄. '+(v==='5'?'Ahora las dos salidas llevan la misma corriente.':`Ahora sale más corriente por ${v==='7'?'I₃':'I₄'}, pero el total sigue siendo el mismo.`);}
  onGroup('#node-share',update);pressed('#node-share','5');update('5');
 }
 if(key==='mallas'){
  let step=0;function update(){const s=loop[step];set('#loop-title',s.title);set('#loop-copy',s.text);bar('#potential-bar',s.potential/12*100);['source','r1','r2'].forEach(k=>$('#loop-'+k).classList.toggle('highlight',s.part===k));$('#loop-next').disabled=step===loop.length-1;result.textContent=step===4?'La vuelta está completa: subida total = caídas totales.':'Sigue la energía por unidad de carga, sin cambiar la corriente del circuito.';}
  $('#loop-next').onclick=()=>{step++;update();};$('#loop-reset').onclick=()=>{step=0;update();};update();
 }
 if(key==='bateria'){
  function update(){const r=+$('#battery-r').value,external=$('#battery-load').value,b=battery(r,external==='open'?6:+external,external==='open');$('#battery-switch').setAttribute('d',external==='open'?'M385 90 445 60':'M385 90H445');bar('#emf-bar',100);bar('#loss-bar',b.loss/b.emf*100);bar('#terminal-bar',b.terminal/b.emf*100);result.textContent=external==='open'?'Circuito abierto: I = 0. No hay caída Ir, así que Vₜ = ε.':r===0?'Fuente ideal: r = 0. Aunque circula corriente, no hay caída interna y Vₜ = ε.':'La batería entrega corriente: Vₜ < ε. Con la misma r, reducir Rₜ aumenta I y la caída interna Ir.';}
  $('#battery-r').value='1';$('#battery-r').onchange=$('#battery-load').onchange=update;update();
 }
 if(key==='capacitores'){
  let charged=false;function update(v){if(v==='charge')charged=true;if(v==='discharge')charged=false;root.classList.toggle('charged',charged);bar('#charge-bar',charged?100:0);set('.path-label',v==='charge'?'Batería':v==='discharge'?'Resistencia':'Abierto');result.textContent=v==='charge'?'Al terminar de cargar: hay +Q y −Q. En corriente continua, el capacitor ideal ya cargado no deja pasar corriente sostenida por esta rama.':v==='isolate'?(charged?'Batería desconectada y circuito abierto: el capacitor ideal conserva la carga y la energía.':'Sin carga y desconectado: las placas siguen neutras.'):'Batería desconectada. Un camino externo con resistencia permite descargarlo: disminuye Q y la energía se transforma en calor. El dibujo muestra el final de la descarga.';}
  onGroup('#capacitor-state',update);update('discharge');pressed('#capacitor-state','discharge');
 }
 if(key==='asociaciones'){
  function update(v){const parallel=v==='parallel';$('#association-diagram').innerHTML=svg('Asociación de capacitores',parallel?`<path d="M80 165H150V80H285M315 80H450V250H315M285 250H150V165M450 165H520" class="wire"/>${line(285,55,285,105)}${line(315,55,315,105)}${line(285,225,285,275)}${line(315,225,315,275)}${text(300,40,'C')}${text(300,315,'C')}${text(65,160,'A')}${text(535,160,'B')}`:`${line(70,165,195,165)}${line(225,165,375,165)}${line(405,165,530,165)}${line(195,110,195,220)}${line(225,110,225,220)}${line(375,110,375,220)}${line(405,110,405,220)}${text(210,85,'C')}${text(390,85,'C')}${text(55,165,'A')}${text(545,165,'B')}`);const tex=parallel?'C_{\\mathrm{eq}}=C_1+C_2':'\\frac{1}{C_{\\mathrm{eq}}}=\\frac{1}{C_1}+\\frac{1}{C_2}';
 const eq=equivalent(1,1,parallel);const fallback=parallel?'C equivalente = C₁ + C₂':'1/C equivalente = 1/C₁ + 1/C₂';
 $('.association-formula').innerHTML=globalThis.katex?globalThis.katex.renderToString(tex,{throwOnError:false,trust:false}):fallback;
 $('.association-formula').insertAdjacentHTML('beforeend',`<br><span class="small">Con dos iguales: ${eq===2?'2C':'C/2'}.</span>`);result.textContent=parallel?'En paralelo, ambos están conectados a los mismos dos nodos: tienen el mismo V. Las cargas se suman; la capacitancia equivalente aumenta.':'En serie, están uno después del otro: comparten la misma magnitud de carga en este conjunto inicialmente neutro. Los voltajes se suman y la capacitancia equivalente es menor que cualquiera de las dos.';}
  onGroup('#association-mode',update);pressed('#association-mode','series');update('series');
 }
 if(key==='capacitancia'){
  function update(){const v=+$('#common-voltage').value;for(const [id,c] of [['a',1],['b',2]]){const n=charge(c,v)*3;$('#charge-'+id).innerHTML=`<div class="plus-signs">${'<span>+</span>'.repeat(n)}</div><div class="minus-signs">${'<span>−</span>'.repeat(n)}</div>`;set('#amount-'+id,`${c*v} ${c*v===1?'vez':'veces'} la carga inicial de C`);}result.textContent='El capacitor 2C almacena el doble de carga que C al mismo voltaje. Al aumentar V, aumenta Q en ambos; sus capacitancias permanecen iguales.';}
  $('#common-voltage').onchange=update;update();
 }
 if(key==='placas'){
  function update(){const a=+$('#plate-area').value,d=+$('#plate-distance').value,k=+$('#plate-k').value,h=70+a*45,gap=40+d*35,l=300-gap/2-15,r=300+gap/2,y=165-h/2;for(const [id,x] of [['left',l],['right',r]]){const p=$('#plate-'+id);p.setAttribute('x',x);p.setAttribute('y',y);p.setAttribute('height',h);}const m=$('#plate-material');m.setAttribute('x',l+20);m.setAttribute('width',gap-10);m.setAttribute('y',y+5);m.setAttribute('height',h-10);m.style.opacity=k===1?.15:.65;$('#distance-line').setAttribute('d',`M${l+15} 285H${r}`);const c=capacitance(a,d,k);set('#capacity-ratio',`C = ${Number(c.toFixed(2)).toLocaleString('es-MX')} × C inicial`);result.textContent=`Área ${a}×, separación ${d}× y K = ${k}. ${c>1?'La capacitancia aumentó.':c<1?'La capacitancia disminuyó.':'La capacitancia es igual a la referencia.'}`;}
  ['area','distance','k'].forEach(x=>$('#plate-'+x).onchange=update);$('#plates-reset').onclick=()=>{['area','distance','k'].forEach(x=>$('#plate-'+x).value='1');update();};update();
 }
 if(key==='dielectricos'){
  function update(v){const inside=v==='in';root.classList.toggle('inserted',inside);bar('#dielectric-c',inside?100:50);bar('#dielectric-q',inside?100:50);result.textContent=inside?'El dieléctrico se polariza: su lado negativo queda orientado hacia la placa positiva. Con V fijo y K = 2, se duplica C y la batería aporta más carga: Q también se duplica.':'Con vacío entre las placas, K = 1. La capacitancia y la carga tienen sus valores de referencia.';}
  onGroup('#dielectric-state',update);pressed('#dielectric-state','out');update('out');
 }
}
