import {factors,prime,split,powers,rnd} from './motor.mjs';
import {m,render} from './ui.mjs';
const host=document.querySelector('#factor-demo');
const examples=[12,18,24,30,36,48,60,72,90,100];
let number=60,path='balanced',open=new Set();
host.innerHTML='<div class="number-picker" role="group" aria-label="Número para factorizar">'+examples.map(n=>`<button data-number="${n}" aria-pressed="${n===60}">${n}</button>`).join('')+'</div><div class="actions"><button id="another-number" class="secondary">Otro número ↻</button><button id="open-all">Desplegar todo</button><button id="reset-tree" class="secondary">Reiniciar árbol</button></div><div class="path-picker" role="group" aria-label="Camino de descomposición"><button data-path="balanced" aria-pressed="true">Camino A</button><button data-path="smallest" aria-pressed="false">Camino B</button></div><p id="path-description"></p><div class="tree-viewport" tabindex="0" aria-label="Árbol de factores; permite desplazamiento horizontal cuando sea necesario"><div id="factor-tree"></div></div><div id="factor-result" aria-live="polite"></div>';
function draw(){let leaves=[],pending=0;function node(n,id='r'){if(prime(n)){leaves.push(n);return `<div class="tree-node"><span class="prime-node" aria-label="${n}, primo">${m(String(n))}<small>primo</small></span></div>`;}if(!open.has(id)){pending++;leaves.push(n);return `<div class="tree-node"><button data-node="${id}" aria-label="Descomponer ${n}" aria-expanded="false">${m(String(n))}</button></div>`;}const [a,b]=split(n,path);return `<div class="tree-node expanded"><span class="parent-node">${m(String(n))}</span><svg class="branches" viewBox="0 0 100 32" preserveAspectRatio="none" aria-hidden="true"><path d="M50 0 C50 16 25 10 25 32 M50 0 C50 16 75 10 75 32"/></svg><div class="tree-children">${node(a,id+'0')}${node(b,id+'1')}</div></div>`;}
 const content=node(number);document.querySelector('#factor-tree').innerHTML=content;document.querySelector('#factor-tree').style.minWidth=Math.max(200,leaves.length*60)+'px';
 const [a,b]=split(number,path);document.querySelector('#path-description').innerHTML='Este camino comienza con '+m(`${number}=${a}\\cdot${b}`)+'. Pulsa los números compuestos para continuar.';
 document.querySelectorAll('[data-node]').forEach(button=>button.onclick=()=>{const id=button.dataset.node;open.add(id);draw();document.querySelector(`[data-node="${id}0"],[data-node="${id}1"]`)?.focus({preventScroll:true});});
 const result=document.querySelector('#factor-result');result.innerHTML=pending?'<p class="tree-note">Las ramas abiertas conservan el valor: '+m(number+'='+leaves.join('\\cdot '))+'.</p>':'<div class="factor-complete"><p>Todos los factores finales son primos.</p><p class="formula">'+m(number+'='+factors(number).join('\\cdot '))+'</p><p class="formula">'+m(number+'='+powers(number))+'</p></div>';
 document.querySelector('#open-all').disabled=pending===0;render();}
function reset(){open=new Set();document.querySelectorAll('[data-number]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.number===number));draw();}
document.querySelectorAll('[data-number]').forEach(b=>b.onclick=()=>{number=+b.dataset.number;reset();});
document.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>{path=b.dataset.path;document.querySelectorAll('[data-path]').forEach(x=>x.setAttribute('aria-pressed',x===b));reset();});
document.querySelector('#another-number').onclick=()=>{const options=examples.filter(n=>n!==number);number=options[rnd(0,options.length-1)];reset();};
document.querySelector('#reset-tree').onclick=reset;
document.querySelector('#open-all').onclick=()=>{function expand(n,id='r'){if(prime(n))return;open.add(id);const [a,b]=split(n,path);expand(a,id+'0');expand(b,id+'1');}expand(number);draw();};
document.querySelector('#show-common').onclick=()=>{const button=document.querySelector('#show-common'),body=document.querySelector('#common-result');body.hidden=!body.hidden;button.setAttribute('aria-expanded',!body.hidden);button.textContent=body.hidden?'Mostrar los factores comunes':'Ocultar la explicación';document.querySelector('.common-factors').classList.toggle('highlight-common',!body.hidden);};
draw();render();
