import {examples,versions,practice,working,correct,choose,roles} from './modelo.mjs';
import {illustratedDiagram} from './figuras.mjs';
const app=document.querySelector('#app'),mode=document.querySelector('main').dataset.mode;
const links={lesson:'explicacion/index.html',practice:'ejercicios/lados-y-angulos/index.html',game:'juegos/misiones-trigonometricas/index.html'};
const base=new URL('../',import.meta.url),href=type=>new URL(links[type],base).href;
const math=s=>`<span class="math" data-tex="${s}">${s}</span>`;
function render(){if(window.katex)app.querySelectorAll('[data-tex]').forEach(el=>window.katex.render(el.dataset.tex,el,{throwOnError:false}));}
window.addEventListener('load',render);
function focus(){app.querySelector('h2')?.focus();}
const diagram=q=>illustratedDiagram(q);
const ratios=()=>`<div class="ratios">${math('\\sin\\theta=\\frac{\\mathrm{C.O.}}{\\mathrm H}')}${math('\\cos\\theta=\\frac{\\mathrm{C.A.}}{\\mathrm H}')}${math('\\tan\\theta=\\frac{\\mathrm{C.O.}}{\\mathrm{C.A.}}')}</div>`;
function menu(){app.innerHTML=`<p class="lead">Un ángulo puede ayudarte a medir lo que falta.</p><div class="hero"><div><span class="badge">PRIMERA EXPLORACIÓN</span><h2>Elige, despeja y calcula</h2><p>Encuentra lados y ángulos de triángulos rectángulos con seno, coseno y tangente.</p><a class="btn" href="${href('lesson')}">Comenzar →</a></div>${diagram(examples[0])}</div><div class="menu-cards"><a href="${href('lesson')}"><span>01 · DESCUBRE</span><h2>Cuatro ejemplos</h2><p>Los tres lados y los ángulos, paso a paso.</p></a><a href="${href('practice')}"><span>02 · PRACTICA</span><h2>Cuatro ejercicios</h2><p>Con ayuda y una calculadora en grados.</p></a><a href="${href('game')}"><span>03 · JUEGA</span><h2>Tres misiones por partida</h2><p>Tres aventuras posibles: nueve problemas en total.</p></a></div>`;render();}
let page=0,reveal=0;
function lesson(){
 const q=examples[page-1],steps=q?working(q):[];
 app.innerHTML=`<section class="panel"><p class="badge">${page===0?'ANTES DE EMPEZAR':`EJEMPLO ${page} DE 4`}</p>${page===0?`<h2 tabindex="-1">Todo depende del ángulo θ</h2><p>La hipotenusa está frente al ángulo recto. Respecto a θ, el cateto opuesto queda enfrente y el adyacente toca el ángulo.</p>${ratios()}<p><strong>Para un lado:</strong> necesitas un ángulo agudo y un lado. Elige la razón que une los datos con la incógnita.</p><p><strong>Para un ángulo:</strong> necesitas dos lados y una función inversa. Un solo lado no basta.</p><div class="notice">Pon tu calculadora en <strong>DEG (grados)</strong>. Usa ${math('\\sin^{-1}')}, ${math('\\cos^{-1}')} o ${math('\\tan^{-1}')} para un ángulo; no son ${math('\\frac{1}{\\sin}')}, ${math('\\frac{1}{\\cos}')} ni ${math('\\frac{1}{\\tan}')}.</div>`:`<h2 tabindex="-1">${q.title}</h2><p>${q.text}</p><div class="two-col"><div>${diagram(q)}<p class="caption">C.O. enfrente de θ · C.A. junto a θ · H. hipotenusa.<br>Dibujo de referencia, no a escala.</p></div><div><div class="steps" aria-live="polite">${steps.slice(0,reveal).map(s=>`<div class="step">${math(s)}</div>`).join('')}</div>${reveal<steps.length?'<button class="btn" id="reveal">Mostrar siguiente paso</button>':'<p class="success">¡Así se calcula!</p>'}${page===4?`<details><summary>¿Y si conozco otros lados?</summary><p>Elige la inversa que use tus dos datos:</p>${math('\\theta=\\sin^{-1}\\left(\\frac{\\mathrm{C.O.}}{\\mathrm H}\\right)')}${math('\\theta=\\cos^{-1}\\left(\\frac{\\mathrm{C.A.}}{\\mathrm H}\\right)')}${math('\\theta=\\tan^{-1}\\left(\\frac{\\mathrm{C.O.}}{\\mathrm{C.A.}}\\right)')}<p>Los tres ángulos suman 180°; los dos agudos, 90°.</p></details>`:''}</div></div>`}<div class="actions">${page?'<button id="back">← Anterior</button>':''}${page<4?'<button class="btn" id="continue">Continuar →</button>':`<a class="btn" href="${href('practice')}">Continuar a los ejercicios →</a>`}</div></section>`;
 app.querySelector('#continue')?.addEventListener('click',()=>{page++;reveal=0;lesson();focus();});app.querySelector('#back')?.addEventListener('click',()=>{page--;reveal=0;lesson();focus();});app.querySelector('#reveal')?.addEventListener('click',()=>{reveal++;lesson();(app.querySelector('#reveal')||app.querySelector('#continue')||app.querySelector('.actions a')).focus();});render();
}
let version=choose(),index=0,cases=[],solved=false;
function start(){index=0;cases=mode==='game'?versions[version].levels:practice();round();}
function round(){
 solved=false;const q=cases[index],angles=['theta','all'].includes(q.target),fields=q.target==='all'?['Ángulo θ','Ángulo α','Ángulo recto']:angles?['Ángulo θ']:['Longitud que falta'];
 app.innerHTML=`<div class="progress-head"><span class="badge">${mode==='game'?versions[version].name:'Entrenamiento'}</span><span>${mode==='game'?'Nivel':'Ejercicio'} ${index+1} de ${cases.length}</span></div><progress max="${cases.length}" value="${index}" aria-label="Retos completados"></progress><section class="panel"><h2 tabindex="-1">${q.title}</h2><p class="question">${q.text}</p><div class="two-col"><div>${diagram(q)}<p class="caption">C.O. enfrente de θ · C.A. junto a θ · H. hipotenusa.<br>Dibujo no a escala.</p></div><div><p class="badge">${angles?'ENCUENTRA '+(q.target==='all'?'LOS TRES ÁNGULOS':'EL ÁNGULO θ'):'ENCUENTRA '+roles[q.target]}</p><form id="answer-form">${fields.map((name,i)=>`<label for="answer-${i}">${name}</label><div class="answer-row"><input id="answer-${i}" type="text" inputmode="decimal" autocomplete="off" required maxlength="32" aria-describedby="answer-help feedback"><span>${angles?'°':'m'}</span></div>`).join('')}<p class="caption" id="answer-help">Usa DEG y redondea tu respuesta a dos decimales cuando sea necesario.</p><button class="btn" type="submit">Comprobar</button></form><p id="feedback" role="status"></p><details><summary>Consultar fórmulas</summary>${ratios()}${angles?`${math('\\theta=\\sin^{-1}\\left(\\frac{\\mathrm{C.O.}}{\\mathrm H}\\right)')}${math('\\theta=\\cos^{-1}\\left(\\frac{\\mathrm{C.A.}}{\\mathrm H}\\right)')}${math('\\theta=\\tan^{-1}\\left(\\frac{\\mathrm{C.O.}}{\\mathrm{C.A.}}\\right)')}<p>El otro ángulo agudo es ${math('\\alpha=90^\\circ-\\theta')}; el recto es 90°.</p>`:'<p>Si la incógnita queda abajo, multiplica por ella y después divide entre la función.</p>'}</details><div id="solution"></div><button class="btn" id="next" hidden>${index+1===cases.length?'Terminar':'Continuar →'}</button></div></div></section>`;
 app.querySelector('form').onsubmit=e=>{e.preventDefault();if(solved)return;const inputs=[...app.querySelectorAll('input')],feedback=app.querySelector('#feedback');if(!correct(q,inputs.map(el=>el.value))){feedback.textContent='Revisa tus datos, el despeje y el modo DEG. Redondea solo al final; puedes intentarlo de nuevo.';feedback.className='notice';inputs.forEach(el=>el.setAttribute('aria-invalid','true'));return;}solved=true;inputs.forEach(el=>{el.readOnly=true;el.removeAttribute('aria-invalid');});feedback.textContent='¡Correcto! Misión resuelta.';feedback.className='success';app.querySelector('[type=submit]').disabled=true;app.querySelector('#solution').innerHTML=working(q).map(s=>`<div class="step">${math(s)}</div>`).join('');app.querySelector('progress').value=index+1;app.querySelector('#next').hidden=false;render();app.querySelector('#next').focus();};
 app.querySelector('#next').onclick=()=>{if(!solved)return;index++;if(index===cases.length)finish();else round();focus();};render();
}
function finish(){app.innerHTML=`<section class="panel celebration"><span class="medal" aria-hidden="true">✦</span><h2 tabindex="-1">¡Lo lograste, Kenia!</h2><p>Resolviste ${cases.length} retos usando lados, ángulos y razones trigonométricas.</p><div class="actions"><button class="btn" id="again">${mode==='game'?'Jugar otra aventura':'Otros ejercicios'}</button>${mode==='practice'?`<a class="btn" href="${href('game')}">Continuar al juego →</a>`:''}</div></section>`;app.querySelector('#again').onclick=()=>{version=choose(version);start();focus();};}
if(mode==='menu')menu();else if(mode==='lesson')lesson();else start();
