import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
import {ACTIVIDADES} from '../recursos/actividades.mjs';
const base=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const write=(path,text)=>writeFileSync(resolve(base,path),text,'utf8');
function frame(title,body,depth,activity=null){
  const up='../'.repeat(depth),links=[['Inicio',''],['Nosotros','nosotros/'],['Biblioteca','biblioteca/'],['Salones','asesores/'],['Contacto','contacto/']];
  const nav=links.map(([label,path])=>`<li><a href="${up}${path}index.html">${label}</a></li>`).join('');
  const brand=`<a class="brand" href="${up}index.html" aria-label="Matemáticas a Domicilio, inicio"><img src="${up}recursos/svg/logo-estrella.svg" width="204" height="48" alt=""></a>`;
  return `<!doctype html>
<html lang="es-MX"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} | Alejandrina | Matemáticas a Domicilio</title><meta name="description" content="${activity?activity.descripcion:'Práctica de sucesiones y series aritméticas y geométricas para Alejandrina.'}"><link rel="icon" href="${up}recursos/svg/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${up}recursos/css/base.css?v=20260902-global1"><link rel="stylesheet" href="estilos.css?v=20260930-series1"><script defer src="${up}recursos/js/navegacion.js?v=20260902-global1"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.18.1/dist/katex.min.css" integrity="sha384-1vdNCNel6Tx/NQa8IR1mGOGKsbGreCkOPfbtPPnUURJ5Tu2PRVfQ/7KLZC+Pi1p1" crossorigin="anonymous"><script defer src="https://cdn.jsdelivr.net/npm/katex@0.18.1/dist/katex.min.js" integrity="sha384-ycJ6GAwiS15LoUPipwJOrWTvkUHl/YqELValBwI5I4awP1EeEQJYarj+w85ntcz7" crossorigin="anonymous"></script>${activity?'<script type="module" src="../../recursos/practica.mjs?v=20260930-series1"></script>':''}</head>
<body><a class="skip-link" href="#contenido">Saltar al contenido</a><header class="site-header"><div class="container header-inner">${brand}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="menu-principal" aria-label="Abrir o cerrar menú" data-menu-toggle><span class="menu-toggle-lines" aria-hidden="true"></span></button><nav class="site-nav" id="menu-principal" aria-label="Navegación principal" data-menu><ul class="nav-list">${nav}</ul></nav></div></header><main class="series-exam" id="contenido" tabindex="-1"${activity?` data-actividad="${activity.id}"`:''}><div class="session-wrap">${body}</div></main><footer class="site-footer"><div class="container footer-grid"><div class="footer-brand">${brand}<p>Asesorías particulares de matemáticas</p></div><nav aria-label="Navegación del pie de página"><ul class="footer-nav">${nav}</ul></nav></div><div class="container footer-legal"><p>© 2026 Matemáticas a Domicilio</p><p><a href="${up}legal/aviso-de-privacidad/index.html">Aviso de Privacidad</a> · <a href="${up}legal/terminos-y-condiciones/index.html">Términos y Condiciones</a></p><p>Mérida, Yucatán, México</p></div></footer></body></html>\n`;
}
write('index.html',frame('Examen series',`<nav class="breadcrumbs" aria-label="Migas de pan"><ol><li><a href="../../../index.html">Salones</a></li><li><a href="../../index.html">Erik</a></li><li><a href="../index.html">Alejandrina</a></li><li aria-current="page">Examen series</li></ol></nav><header class="hero"><p class="eyebrow">Alejandrina · Asesor Erik</p><h1>Examen series</h1><p class="lead">Sucesiones y series aritméticas y geométricas. Elige una actividad y practica a tu ritmo.</p></header><section class="activity-grid" aria-label="Actividades de la sesión">${ACTIVIDADES.map(a=>`<article class="activity-card"><span class="activity-number">${String(a.numero).padStart(2,'0')}</span><h2>${a.titulo}</h2><p>${a.descripcion}</p><a class="button primary" href="ejercicios/${a.id}/index.html">${a.numero===1?'Comenzar':'Abrir actividad'} →</a></article>`).join('')}</section><nav class="page-nav" aria-label="Volver"><a class="button" href="../index.html">← Casillero de Alejandrina</a></nav>`,4));
write('estilos.css','@import url("recursos/sesion.css?v=20260930-series1");\n');
for(const [i,a] of ACTIVIDADES.entries()){
  const dir=`ejercicios/${a.id}`;mkdirSync(resolve(base,dir),{recursive:true});
  const next=ACTIVIDADES[i+1],previous=ACTIVIDADES[i-1];
  const filter=a.filtro?'<fieldset class="type-filter"><legend>Tipo de sucesión</legend><div><button class="button" type="button" data-filter="ambas" aria-pressed="true">Ambas</button><button class="button" type="button" data-filter="aritmetica" aria-pressed="false">Solo aritméticas</button><button class="button" type="button" data-filter="geometrica" aria-pressed="false">Solo geométricas</button></div></fieldset>':'';
  const cases=a.secciones.map((c,n)=>`<section class="case" data-caso="${c.id}" id="${c.id}" aria-labelledby="${c.id}-title"><p class="eyebrow">${a.secciones.length>1?`Caso ${n+1}`:'Práctica'}</p><h2 id="${c.id}-title" tabindex="-1">${c.titulo}</h2><p class="case-progress"></p><div class="problem"></div></section>`).join('');
  const body=`<nav class="breadcrumbs" aria-label="Migas de pan"><ol><li><a href="../../../index.html">Alejandrina</a></li><li><a href="../../index.html">Examen series</a></li><li aria-current="page">${a.titulo}</li></ol></nav><header class="hero"><p class="eyebrow">Actividad ${a.numero} · Examen series</p><h1>${a.titulo}</h1><p class="lead">${a.descripcion}</p></header>${filter}<noscript><p>Activa JavaScript para resolver los ejercicios.</p></noscript>${cases}<nav class="page-nav" aria-label="Recorrido de la sesión">${previous?`<a class="button" href="../${previous.id}/index.html">← Anterior</a>`:''}<a class="button" href="../../index.html">Menú de la sesión</a><a class="button primary" href="${next?`../${next.id}/index.html`:'../../index.html'}">${next?'Continuar →':'Volver al menú →'}</a></nav>`;
  write(`${dir}/index.html`,frame(a.titulo,body,6,a));write(`${dir}/estilos.css`,'@import url("../../recursos/sesion.css?v=20260930-series1");\n');
  write(`${dir}/ejercicio.json`,JSON.stringify({id:`examen-series-${a.id}-alejandrina`,tipo:'ejercicio',sesion:'examen-series-alejandrina',usuario:'alejandrina',titulo:a.titulo,descripcion:a.descripcion,estado:'publicado',ruta:`/asesores/erik/alejandrina/examen-series/${dir}/`},null,2)+'\n');
  write(`${dir}/README.md`,`# ${a.titulo}\n\nActividad ${a.numero} de Examen series, Alejandrina → Erik.\n\n${a.descripcion}\n\nSecciones independientes, en orden: ${a.secciones.map(c=>c.titulo).join('; ')}. ${a.filtro?'Selector Ambas / Solo aritméticas / Solo geométricas.':''}\n\nReutiliza exclusivamente los recursos de esta sesión: \\recursos\\actividades.mjs, modelo.mjs, fracciones.mjs, practica.mjs y sesion.css. Generadores progresivos y validación exacta, salvo los mini exámenes, que utilizan bancos fijos. Sin teoría adicional. La notación se renderiza con KaTeX 0.18.1 (CDN con SRI y fuente LaTeX de respaldo). Datos y avance en memoria; no se recopilan datos personales.\n\nConservar index.html, estilos.css, ejercicio.json, esta ruta y su identidad. La navegación enlaza a actividades existentes y al menú. La especificación completa está en ../../ENCARGO.md, el estado de implementación en ../../ETAPAS.md y las reglas de arquitectura en ../../README.md.\n\nVerificar blancos, error/acierto, reintentos, siguiente ejercicio, filtros cuando corresponda, fracciones equivalentes, teclado, móvil, escritorio, consola y LaTeX. Desde la raíz ejecutar pruebas del modelo de sesión, npm run catalogo y npm run validar.\n`);
}
const metadata=JSON.parse(readFileSync(resolve(base,'sesion.json'),'utf8'));metadata.descripcion=`Práctica de sucesiones y series aritméticas y geométricas: ${ACTIVIDADES.map(a=>a.titulo.toLowerCase()).join(', ')}.`;metadata.objetivo='Practicar identificación, parámetros, términos, posiciones, sumas y medios de sucesiones aritméticas y geométricas con validación exacta y dificultad progresiva.';metadata.componentes.ejercicios=true;write('sesion.json',JSON.stringify(metadata,null,2)+'\n');
console.log(`Sesión actualizada: ${ACTIVIDADES.length} actividades reales.`);
