import {middle,means,direct,missing,tramo,application,meansGame,sumsGame} from './motor.mjs';
import {task,render,ribbon,formula} from './ui.mjs';
const topic=document.body.dataset.topic,root=document.querySelector('#practice');
const makers={medios:middle,varios:means,suma:direct,datos:missing,tramos:tramo,aplicaciones:application};
if(root){let previous='';const generate=()=>{let r,key;do{r=makers[topic](document.querySelector('#case')?.value);key=JSON.stringify(r);}while(key===previous);previous=key;task(root,r);};document.querySelector('#new').onclick=generate;document.querySelector('#case')?.addEventListener('change',generate);generate();}

const count=document.querySelector('#mean-count');
if(count){const update=()=>{const k=Number(count.value),d=24/(k+1),values=Array.from({length:k+2},(_,i)=>4+i*d),view=document.querySelector('#count-view');let position=0;view.innerHTML=ribbon(values)+`<p><strong>${k} medios</strong> · ${k+2} términos · <strong>${k+1} saltos</strong></p>`+formula(`d=\\frac{28-4}{${k}+1}=${d}`)+'<button type="button" class="walk">Dar un salto →</button><div class="walk-reading" role="status">Comienza en 4.</div>';const button=view.querySelector('.walk');view.querySelector('.term').classList.add('current-term');button.onclick=()=>{position=position===values.length-1?0:position+1;view.querySelectorAll('.term').forEach((el,i)=>el.classList.toggle('current-term',i===position));view.querySelector('.walk-reading').innerHTML=position?formula(`${values[position-1]}+${d}=${values[position]}`):'<p>Comienza en 4.</p>';button.textContent=position===values.length-1?'Repetir recorrido ↺':'Dar un salto →';render(view);};render();};count.oninput=update;update();}
const pairs=document.querySelector('#pairs');
if(pairs){let active=false;document.querySelector('#pair-toggle').onclick=()=>{active=!active;pairs.classList.toggle('paired',active);document.querySelector('#pair-toggle').setAttribute('aria-pressed',String(active));document.querySelector('#pair-result').innerHTML=active?formula('2S_5=5(20)\\qquad S_5=50')+'<p>Cada columna suma 20. Las dos filas contienen el mismo total: por eso dividimos entre dos.</p>':'<p>Invierte una copia de la fila y empareja sus extremos.</p>';render();};}

const game=document.querySelector('#game');
if(game){const isMeans=topic==='juego-medios',total=isMeans?6:7,maker=isMeans?meansGame:sumsGame;let round=0,clean=0,reviewed=0;const next=document.querySelector('#next-round'),status=document.querySelector('#game-status'),restart=document.querySelector('#restart');
 function progress(){status.innerHTML=`<p>${reviewed} de ${total} retos completados</p><svg class="game-trail" viewBox="0 0 500 110" aria-hidden="true">${isMeans?'<path d="M10 85Q250 120 490 85" fill="none" stroke="#afd9da" stroke-width="8"/><path d="M15 35H485" stroke="#a4b9a8" stroke-width="3"/>':'<path d="M10 100H490" stroke="#b8c8b9" stroke-width="2"/>'}${Array.from({length:total},(_,i)=>`<rect class="${i<reviewed?'built':''}" x="${25+i*(450/total)}" y="${isMeans?25:90-i*9}" width="${420/total}" height="${isMeans?35:10+i*9}" rx="6" fill="${i<reviewed?(isMeans?'#659884':'#a18cb7'):'#e3e9df'}" stroke="${i<reviewed?'#497c64':'#aabdaa'}" stroke-dasharray="${i<reviewed?'0':'4 3'}"/>`).join('')}</svg><progress max="${total}" value="${reviewed}" aria-label="Retos completados"></progress><p class="input-note">Cada pieza representa un reto completado.</p>`;}
 function load(){next.hidden=true;progress();task(game,maker(round),({assisted})=>{reviewed++;if(!assisted)clean++;progress();next.hidden=false;next.textContent=round===total-1?'Ver cierre':'Siguiente reto →';});}
 next.onclick=()=>{round++;if(round===total){game.innerHTML=`<div class="finish"><span class="finish-mark" aria-hidden="true">✦</span><h3 tabindex="-1">${isMeans?'Ya puedes construir una progresión.':'Ya puedes elegir qué calcular.'}</h3><p>Completaste ${total} retos: ${clean} sin correcciones ni solución mostrada y ${total-clean} con revisión.</p><p>${isMeans?'Recuerda: k medios crean k + 1 saltos. Comprueba que todos sean iguales.':'Un término responde «en esa posición». Una suma responde «en total». Si faltan datos, encuéntralos primero.'}</p></div>`;next.hidden=true;game.querySelector('h3').focus();}else{load();game.querySelector('h3').focus();}};
 restart.onclick=()=>{round=0;clean=0;reviewed=0;load();game.querySelector('h3').focus();};load();
}
render();window.addEventListener('load',()=>render());
