import {parse,close,fmt,shuffle} from './motor.mjs';
export const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function fallback(s){let i=0;function group(){if(s[i]==='{'){i++;return read('}');}return esc(s[i++]||'');}function read(end=''){let out='';while(i<s.length){if(end&&s[i]===end){i++;break;}if(s.startsWith('\\frac',i)){i+=5;out+='<span class="fraction"><span>'+group()+'</span><span>'+group()+'</span></span>';}else if(s.startsWith('\\text',i)){i+=5;out+=group();}else if(s.startsWith('\\qquad',i)){i+=6;out+='　';}else if(s.startsWith('\\quad',i)){i+=5;out+='　';}else if(s.startsWith('\\cdot',i)){i+=5;out+=' × ';}else if(s.startsWith('\\,',i)){i+=2;out+=' ';}else if(s[i]==='^'||s[i]==='_'){const tag=s[i++]==='^'?'sup':'sub';out+='<'+tag+'>'+group()+'</'+tag+'>';}else if(s[i]==='{'){i++;out+=read('}');}else out+=esc(s[i++]);}return out;}return read();}
export const normalizeMath=s=>s.replace(/_(\d+)/g,'_{$1}');
export const m=value=>{const s=normalizeMath(value);return `<span class="math" data-math="${esc(s)}">${fallback(s)}</span>`;};
export const formula=s=>`<div class="formula">${m(s)}</div>`;
export function render(root=document){root.querySelectorAll('[data-math]').forEach(el=>{el.dataset.math=normalizeMath(el.dataset.math);if(el.dataset.rendered===el.dataset.math)return;if(window.katex){window.katex.render('\\displaystyle '+el.dataset.math,el,{throwOnError:false});el.dataset.rendered=el.dataset.math;}else el.innerHTML=fallback(el.dataset.math);});}
export function ribbon(values,hidden=[]){return `<div class="sequence" aria-label="Progresión">${values.map((v,i)=>`${i?'<span class="jump" aria-hidden="true">→</span>':''}<span class="term ${hidden.includes(i)?'missing':''}" ${hidden.includes(i)?`aria-label="Término faltante en posición ${i+1}"`:''}>${hidden.includes(i)?'?':fmt(v)}</span>`).join('')}</div>`;}

export function task(root,r,onDone=()=>{}){
 let assisted=false,completed=false;
 root.innerHTML=`<h3 tabindex="-1" class="task-title">${r.prompt}</h3>${r.values?ribbon(r.values,r.hidden):''}<div class="plan"></div><div class="task-steps ${r.kind==='varios'?'means-steps':''}"></div><div class="task-complete" role="status"></div>`;
 const steps=root.querySelector('.task-steps');
 function finish(){if(completed)return;completed=true;const area=root.querySelector('.task-complete');area.innerHTML=`<p class="success"><span class="spark" aria-hidden="true">✦</span> ${assisted?'Procedimiento revisado.':'Reto resuelto.'}</p>${r.values?`<p>Comprueba la progresión completa:</p>${ribbon(r.values)}<button class="check-jumps" type="button" aria-expanded="false">Verificar los saltos</button><div class="jump-proof"></div>`:''}`;if(r.values)area.querySelector('.check-jumps').onclick=e=>{const open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',String(open));area.querySelector('.jump-proof').innerHTML=open?r.values.slice(1).map((v,i)=>formula(`${v<0?'('+v+')':v}-${r.values[i]<0?'('+r.values[i]+')':r.values[i]}=${v-r.values[i]}`)).join(''):'';render(area);};onDone({assisted});}
 function choices(prompt,options,answer,explanation,done){const area=root.querySelector('.plan');area.innerHTML=`<p><strong>${prompt}</strong></p><div class="choices"></div><p class="choice-feedback" role="status"></p>`;shuffle(options).forEach(text=>{const b=document.createElement('button');b.type='button';b.textContent=text;area.querySelector('.choices').append(b);b.onclick=()=>{if(text!==answer){assisted=true;b.classList.add('wrong');area.querySelector('.choice-feedback').textContent=explanation+' Vuelve a elegir.';return;}area.querySelectorAll('button').forEach(el=>el.disabled=true);b.classList.add('correct');area.querySelector('.choice-feedback').textContent='✓ '+explanation;done();};});}
 function next(index){if(index===r.steps.length){finish();return;}const s=r.steps[index],box=document.createElement('div'),meansFill=r.kind==='varios'&&index===2;box.className='step'+(meansFill?' means-fill':'');steps.append(box);
  const input=(f,i,value='')=>`<input name="value-${i}" aria-label="${esc(f.label.replaceAll('\\text','').replace(/[{}]/g,''))}" autocomplete="off" inputmode="text" value="${value}" required>`;
  const field=(f,i)=>`<label>${m(f.label)} = ${input(f,i)}</label>`;
  let fields=`<div class="fields">${s.fields.map(field).join('')}</div>`;
  if(meansFill)fields=`<div class="fill-sequence"><span class="fixed-end"><small>Inicio</small><strong>${fmt(r.a)}</strong></span>${s.fields.map((f,i)=>`<span class="jump" aria-hidden="true">→</span><label>${m(f.label)}${input(f,i)}</label>`).join('')}<span class="jump" aria-hidden="true">→</span><span class="fixed-end"><small>Final</small><strong>${fmt(r.b)}</strong></span></div>`;
  const left=s.fields.findIndex(f=>f.label==='a_{'+r.p+'}'),right=s.fields.findIndex(f=>f.label==='a_{'+r.q+'}'),hasRange=Number.isInteger(r.p)&&left>=0&&right>=0;
  if(hasRange){
   const positions=[...new Set([1,2,3,...Array.from({length:r.q-r.p+1},(_,i)=>r.p+i)])].sort((a,b)=>a-b);
   fields=`<div class="fields">${s.fields.map((f,i)=>i===left||i===right?'':field(f,i)).join('')}</div><p class="input-note">Arriba está la posición; abajo, su valor. Completa los extremos del tramo: cuando sean correctos, se llenará el interior.</p><div class="term-table" role="group" aria-label="Posiciones y valores de la progresión">${positions.map((pos,i)=>{
    const fIndex=pos===r.p?left:pos===r.q?right:-1,isInside=pos>=r.p&&pos<=r.q,value=r.a+(pos-1)*r.d;
    return (i&&pos>positions[i-1]+1?'<div class="table-gap" aria-label="Posiciones omitidas">…</div>':'')+`<div class="term-cell ${isInside?'in-range':''}"><span class="position-title">Posición ${pos}</span><span class="position-symbol">${m('a_{'+pos+'}')}</span>${fIndex>=0?input(s.fields[fIndex],fIndex,pos<=3?value:''):pos<=3?`<strong>${fmt(value)}</strong><small>Dado</small>`:`<output data-position="${pos}">—</output>`}</div>`;
   }).join('')}</div><p class="range-feedback" role="status"></p>`;
  }
  box.innerHTML=`<h4 tabindex="-1">${s.title}</h4>${r.kind==='varios'&&index<2?`<p class="step-data">Entre <strong>${fmt(r.a)}</strong> y <strong>${fmt(r.b)}</strong> · ${r.k} medios</p>`:''}<form>${fields}<div class="actions"><button type="submit" class="primary">Comprobar</button><button type="button" class="hint">Pista</button><button type="button" class="show">Ver cómo se hace</button></div></form><p class="feedback" role="status"></p><div class="working"></div>`;
  const orderedInputs=s.fields.map((_,i)=>box.querySelector('[name="value-'+i+'"]'));
  function syncRange(){if(!hasRange)return;const ready=close(parse(orderedInputs[left].value),s.fields[left].answer)&&close(parse(orderedInputs[right].value),s.fields[right].answer);box.querySelectorAll('[data-position]').forEach(el=>{el.textContent=ready?fmt(r.a+(Number(el.dataset.position)-1)*r.d):'—';el.classList.toggle('auto-filled',ready);});box.querySelector('.range-feedback').textContent=ready?'Los extremos coinciden. Los valores interiores se completaron con la misma diferencia.':'';}
  if(hasRange){orderedInputs.forEach(el=>el.addEventListener('input',syncRange));syncRange();}
  const feedback=box.querySelector('.feedback');
  function solve(help){if(help)assisted=true;orderedInputs.forEach((el,i)=>{el.value=String(s.fields[i].answer);el.disabled=true;el.removeAttribute('aria-invalid');});syncRange();box.querySelectorAll('button').forEach(el=>el.disabled=true);feedback.textContent=help?'Revisa la operación y continúa.':'✓ Coincide.';feedback.classList.add('success');box.querySelector('.working').innerHTML=formula(s.tex)+(s.explanation?`<p>${s.explanation}</p>`:'');render(box);next(index+1);}
  box.querySelector('form').onsubmit=e=>{e.preventDefault();const inputs=orderedInputs,bad=inputs.filter((el,i)=>!close(parse(el.value),s.fields[i].answer));inputs.forEach(el=>el.setAttribute('aria-invalid',String(bad.includes(el))));if(bad.length){assisted=true;feedback.textContent=bad.some(el=>!Number.isFinite(parse(el.value)))?'Escribe un número, un decimal (1.5 o 1,5) o una fracción (3/2).':s.hint;bad[0].focus();return;}solve(false);};
  box.querySelector('.hint').onclick=()=>{feedback.textContent=s.hint;};box.querySelector('.show').onclick=()=>solve(true);render(box);
 }
 if(r.choice)choices('Elige la explicación.',r.choice.options,r.choice.answer,r.choice.explanation,finish);
 else if(r.plan)choices('Antes de calcular: ¿qué necesitas?', ['Encontrar un término','Sumar todos los términos','Sumar un tramo'],r.plan,r.plan==='Encontrar un término'?'Se pide una sola posición.':r.plan==='Sumar un tramo'?'Se pide el total de un intervalo, incluidos sus dos extremos.':'Se pide el total acumulado desde la primera posición.',()=>next(0));
 else next(0);render(root);
}
