// Cuatro preguntas diferentes por bloque; la primera respuesta es la correcta antes de barajar.
const bank={
coulomb:[
 ['Dos cargas negativas están separadas. ¿Cómo interactúan?','Se repelen porque tienen el mismo signo.','Se atraen porque ambas son negativas.','No interactúan porque no hay una carga positiva.','El signo negativo no elimina la carga. Cargas del mismo signo se repelen. Las fuerzas sobre ambas tienen igual magnitud y sentidos opuestos.'],
 ['Duplicamos una carga y mantenemos la otra y la distancia. ¿Qué ocurre con la fuerza?','Su magnitud se duplica.','Su magnitud se cuadruplica.','Su magnitud se reduce a la mitad.','La fuerza es directamente proporcional a cada carga: duplicar sólo una duplica el producto de sus magnitudes.'],
 ['Duplicamos la distancia entre dos cargas sin cambiarlas. ¿Qué ocurre con la fuerza?','Queda en una cuarta parte.','Queda en la mitad.','Se duplica.','La distancia está al cuadrado en el denominador. Al multiplicar la distancia por dos, el denominador se multiplica por cuatro.'],
 ['Invertimos el signo de una carga, conservando magnitudes y distancia. ¿Qué cambia?','La atracción pasa a repulsión o viceversa; la magnitud no cambia.','La fuerza desaparece.','La magnitud de la fuerza siempre se duplica.','El valor absoluto del producto no cambia. Los signos determinan el sentido de la interacción, no su magnitud en este modelo.']
],
corriente:[
 ['¿Qué significa una corriente promedio de 3 A?','Atraviesan la sección 3 C por segundo, en promedio.','Cada electrón se desplaza a 3 metros por segundo.','El cable contiene exactamente 3 electrones.','La corriente es carga que atraviesa una sección dividida entre el tiempo. No mide la velocidad individual de los electrones.'],
 ['La misma carga atraviesa una sección en la mitad de tiempo. ¿Qué ocurre con la corriente promedio?','Se duplica.','Se reduce a la mitad.','Permanece igual.','La misma cantidad de carga pasa más rápidamente: al dividir entre la mitad de tiempo obtenemos el doble de corriente.'],
 ['En un metal, ¿cómo se relacionan electrones y corriente convencional?','El movimiento neto de electrones es opuesto a la corriente convencional.','Siempre tienen el mismo sentido.','Los electrones permanecen inmóviles cuando hay corriente.','Los electrones tienen carga negativa. La corriente convencional se define por el sentido del movimiento de carga positiva.'],
 ['¿Qué caracteriza a la corriente directa?','Mantiene una dirección; su magnitud no tiene que ser perfectamente constante.','Su magnitud nunca puede variar.','Sólo existe cuando el circuito está abierto.','Dirección y magnitud son aspectos diferentes. En esta sesión se usa además el caso estable, con valores constantes durante el intervalo.']
],
voltaje:[
 ['¿Qué indica una diferencia de potencial de 12 V?','Una diferencia de 12 J de energía por cada coulomb de carga.','Una corriente obligatoria de 12 A.','La presencia de 12 C almacenados en cada cable.','El voltaje es diferencia de energía potencial por unidad de carga. No indica por sí solo la corriente ni la carga total.'],
 ['¿En qué unidad se mide la fuerza electromotriz de una fuente?','En volts.','En newtons.','En amperes.','Pese al nombre, la fem no es una fuerza mecánica. Expresa energía que la fuente proporciona por unidad de carga.'],
 ['Duplicamos el voltaje entre dos puntos. Para la misma carga positiva, ¿qué ocurre con la diferencia de energía?','Se duplica.','Se mantiene igual.','Se reduce a la mitad.','La magnitud del cambio de energía es carga por diferencia de potencial. Con carga fija, es proporcional al voltaje.'],
 ['¿Puede haber voltaje entre los terminales de una batería sin corriente en un circuito externo?','Sí; la diferencia de potencial puede existir aunque el circuito externo esté abierto.','No; voltaje y corriente son la misma magnitud.','Sí, pero sólo si la resistencia es cero.','Una fuente puede mantener una diferencia de potencial entre terminales. Para corriente sostenida en el ejemplo se necesita una trayectoria cerrada.']
],
resistencia:[
 ['Comparamos cobre y nicromo con la misma geometría y temperatura. ¿Cuál tiene mayor resistencia?','El nicromo, porque su resistividad es mayor en la tabla de referencia.','El cobre, porque es mejor conductor.','Siempre son iguales si tienen igual longitud.','Con longitud y área iguales, la resistencia es proporcional a la resistividad del material.'],
 ['¿Por qué la tabla de resistividades indica 20 °C?','Porque la resistividad depende de las condiciones, incluida la temperatura.','Porque ningún conductor funciona a otra temperatura.','Porque resistividad y temperatura tienen la misma unidad.','La tabla es una referencia a una temperatura determinada. Sus valores no son constantes universales para cualquier temperatura o composición.'],
 ['Dos cables tienen igual material y área. Uno mide el doble. ¿Cuál ofrece más resistencia?','El doble de largo ofrece el doble de resistencia.','El corto ofrece el doble de resistencia.','Ambos ofrecen la misma resistencia.','Para un conductor uniforme, la resistencia es proporcional a la longitud cuando material, sección y temperatura permanecen iguales.'],
 ['Mantenemos material y longitud, pero duplicamos el área transversal. ¿Cómo cambia la resistencia?','Se reduce a la mitad.','Se duplica.','Se cuadruplica.','El área está en el denominador de la expresión de resistencia. Mayor sección permite más flujo para el mismo voltaje en este modelo.'],
 ['¿Qué diferencia hay entre resistencia y resistividad?','La resistividad caracteriza al material; la resistencia también depende de la geometría del objeto.','Son dos nombres para la misma cantidad y tienen la misma unidad.','La resistividad depende sólo de la longitud del cable.','La resistividad se expresa en ohm-metro. La resistencia de una pieza concreta se expresa en ohm y depende de longitud y sección.'],
 ['Duplicamos el diámetro de un alambre circular sin cambiar material ni longitud. ¿Cómo cambia su resistencia?','Queda en una cuarta parte.','Queda en la mitad.','Se duplica.','El radio también se duplica. El área circular es proporcional al radio al cuadrado: se cuadruplica, y la resistencia queda dividida entre cuatro.']
],
ohm:[
 ['Con resistencia constante en un resistor óhmico, ¿qué ocurre si duplicamos el voltaje?','La corriente se duplica.','La corriente se reduce a la mitad.','La corriente permanece igual.','La corriente es voltaje dividido entre resistencia. A resistencia fija, la corriente es directamente proporcional al voltaje.'],
 ['Con voltaje constante, duplicamos la resistencia. ¿Cómo cambia la corriente?','Se reduce a la mitad.','Se duplica.','Se cuadruplica.','La corriente es inversamente proporcional a la resistencia cuando se conserva el voltaje aplicado.'],
 ['¿La Ley de Ohm con resistencia constante describe cualquier dispositivo en toda situación?','No; se aplica a elementos óhmicos bajo condiciones apropiadas.','Sí; la resistencia siempre es constante sin importar el dispositivo.','Sólo se aplica a fuentes sin ningún conductor.','Muchos dispositivos tienen respuestas no lineales o cambian con la temperatura. Aquí trabajamos con resistores óhmicos y condiciones constantes.'],
 ['Queremos la misma corriente con el doble de resistencia. ¿Qué voltaje necesitamos?','El doble de voltaje.','La mitad de voltaje.','El mismo voltaje.','En la relación entre voltaje, corriente y resistencia, a corriente fija el voltaje necesario es proporcional a la resistencia.']
],
potencia:[
 ['¿Qué significa una potencia de 20 W?','Se transfieren o transforman 20 J de energía por segundo.','El aparato almacena exactamente 20 J.','Circulan siempre 20 A.','Potencia y energía son magnitudes distintas. La potencia mide la rapidez de transferencia o transformación de energía.'],
 ['Mantenemos la corriente y duplicamos el voltaje. ¿Cómo cambia la potencia eléctrica?','Se duplica.','Se reduce a la mitad.','Permanece igual.','La potencia es el producto de voltaje y corriente. Si uno se duplica y el otro se mantiene, el producto se duplica.'],
 ['¿De dónde salen las expresiones de potencia en función de corriente y resistencia?','De combinar la potencia eléctrica con la Ley de Ohm.','Son leyes independientes que no se pueden relacionar.','De suponer que voltaje y corriente son iguales.','Sustituir el voltaje por corriente por resistencia produce la expresión con corriente al cuadrado. Se usa para resistores óhmicos.'],
 ['¿Cómo transforma energía eléctrica una lámpara?','En luz y también en energía térmica.','Toda se transforma exclusivamente en luz.','La energía desaparece cuando la corriente pasa.','La energía se conserva: puede transformarse en diferentes formas. En una lámpara no toda la potencia eléctrica termina como luz visible.']
],
joule:[
 ['¿De dónde procede la energía que calienta un resistor?','De la energía eléctrica suministrada por la fuente y transferida al material.','La resistencia crea energía nueva.','De que desaparecen los electrones al atravesarlo.','Las cargas móviles transfieren energía al material mediante interacciones microscópicas. La fuente suministra la energía; el resistor no la crea.'],
 ['Con resistencia constante, duplicamos la corriente. ¿Cómo cambia la potencia disipada?','Se cuadruplica.','Se duplica.','Se reduce a la mitad.','La potencia es proporcional al cuadrado de la corriente. Duplicar la corriente multiplica ese cuadrado por cuatro.'],
 ['Si mantenemos el voltaje y aumentamos la resistencia, ¿aumenta necesariamente la potencia?','No; en el resistor óhmico disminuye porque baja la corriente.','Sí; más resistencia siempre significa más potencia.','La potencia nunca depende de la resistencia.','Hay que indicar qué se mantiene constante. A voltaje fijo, la potencia es voltaje al cuadrado dividido entre resistencia.'],
 ['¿Podemos deducir una temperatura exacta sólo con la potencia disipada?','No; también hacen falta propiedades térmicas, tiempo y condiciones de intercambio de calor.','Sí; un watt siempre equivale a un grado Celsius.','Sí; basta con conocer el voltaje.','Potencia es energía por tiempo, no temperatura. La visualización térmica de esta sesión es cualitativa y no calcula grados.']
],
repaso:[
 ['¿Qué representa 48 V?','Una diferencia de potencial o voltaje.','Una intensidad de corriente.','Una cantidad de carga.','V después del número es el símbolo de volt. La diferencia de potencial se interpreta como energía por unidad de carga entre dos puntos.'],
 ['¿Qué representa 20 W?','Una potencia.','Una energía total.','Una resistencia.','W es el símbolo de watt. Indica una tasa de transferencia o transformación de energía, no una cantidad total de energía.'],
 ['¿Qué representa 150 mA?','Una intensidad de corriente.','Una diferencia de potencial.','Una resistencia.','A es el símbolo de ampere. El prefijo mili indica una milésima; 150 mA equivalen a 0.150 A.'],
 ['¿Qué representa 25 μC?','Una cantidad de carga eléctrica.','Una potencia.','Una longitud de cable.','C es coulomb. μ es micro: una millonésima. Se conserva el símbolo griego para no confundir el prefijo.'],
 ['¿Qué representa 2.4 kΩ?','Una resistencia.','Una resistividad.','Una corriente.','Ω es ohm, unidad de resistencia. k multiplica por mil: 2.4 kΩ son 2400 Ω.'],
 ['¿Por qué M y m no son intercambiables?','M significa mega y m significa mili: representan factores diferentes.','Ambos significan metro en cualquier contexto.','Las mayúsculas de los prefijos no importan.','Mega multiplica por un millón; mili multiplica por una milésima. El símbolo y su mayúscula o minúscula forman parte de la unidad.']
]};
export const questions=Object.entries(bank).flatMap(([topic,rows])=>rows.map(([question,answer,b,c,explanation],i)=>({id:`${topic}-${i}`,topic,question,answer,options:[answer,b,c],explanation})));
