import {num,quantity,ut,units,parse,close,shuffle} from './motor.mjs';
export const math=t=>`<span class="math" data-tex="${t.replaceAll('"','&quot;')}">${t.replace(/\^\{([^}]+)\}/g,'<sup>$1</sup>').replaceAll('\\mu','μ').replaceAll('\\Omega','Ω')}</span>`;
export const formula=t=>`<div class="formula">${math(t)}</div>`;
export function render(root=document){root.querySelectorAll('[data-tex]').forEach(el=>{if(window.katex&&el.dataset.rendered!==el.dataset.tex){window.katex.render('\\displaystyle '+el.dataset.tex,el,{throwOnError:false});el.dataset.rendered=el.dataset.tex;}});}
export function conceptual(root,q){root.innerHTML=`<h3>${q.question}</h3><div class="answers"></div><div class="response" role="status"></div>`;const choices=shuffle(q.options);choices.forEach(text=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>{root.querySelectorAll('button').forEach(el=>{el.disabled=true;if(el.textContent===q.answer)el.classList.add('correct');});const ok=text===q.answer;b.classList.add(ok?'correct':'incorrect');root.querySelector('.response').innerHTML=`<p class="${ok?'good':'retry'}">${ok?'✓ ¡Correcto!':'Revisa el razonamiento.'}</p><h4>Solución</h4><p><strong>${q.answer}</strong></p><p>${q.explanation}</p>`;};root.querySelector('.answers').append(b);});}
export function fullSolution(r){return `<section class="solution"><h3>Solución</h3><h4>Datos y conversiones al SI</h4>${r.data.map(d=>formula(`${d.symbol}=${quantity(d.value,d.unit)}=${quantity(d.si,d.siUnit)}`)).join('')}<h4>Relación física</h4>${formula(r.formula)}<h4>Despeje para encontrar ${math(r.target)}</h4>${formula(r.rearranged)}${r.prep.length?'<h4>Preparación</h4>'+r.prep.map(formula).join(''):''}<h4>Sustitución y operación</h4>${formula(`${r.substitution}\\approx${quantity(r.answer,r.unit)}`)}<h4>Resultado e interpretación</h4>${formula(`${r.target}\\approx${quantity(r.answer,r.unit)}`)}<p>${r.interpretation}</p></section>`;}
export function numericActivity(root,r){
 root.innerHTML=`<h3>Encuentra ${math(r.target)}</h3>${r.material?`<p>Material: <strong>${r.material}</strong>, a aproximadamente 20 °C.</p>`:''}<div class="given">${r.data.map(d=>formula(`${d.symbol}=${quantity(d.value,d.unit)}`)).join('')}</div><h4>Convierte al SI</h4><form class="conversion-form"><div class="conversions">${r.data.map((d,i)=>units[d.unit][1]===1?`<div class="known-si">${math(`${d.symbol}=${quantity(d.si,d.siUnit)}`)} <span>Ya está en SI.</span></div>`:`<label>${math(`${d.symbol}=${quantity(d.value,d.unit)}`)} <span>→</span><input name="conversion-${i}" aria-label="${d.symbol} en ${ut(d.siUnit)}" inputmode="decimal" autocomplete="off" required> ${math(ut(d.siUnit))}</label>`).join('')}</div><button type="submit">Comprobar conversiones</button></form><p class="conversion-feedback" role="status"></p><div class="formula-stage"></div><div class="answer-stage"></div><div class="solution-stage"></div>`;
 const convert=root.querySelector('.conversion-form');
 convert.onsubmit=e=>{e.preventDefault();const bad=r.data.filter((d,i)=>units[d.unit][1]!==1&&!close(parse(convert.elements[`conversion-${i}`].value),d.si,1e-6));if(bad.length){root.querySelector('.conversion-feedback').innerHTML=`Revisa ${bad.map(d=>math(d.symbol)).join(', ')}. ${bad.map(d=>d.unit==='mm2'?'Para pasar de mm² a m², multiplica por 10⁻⁶: el factor de longitud se eleva al cuadrado.':d.unit==='min'?'Para pasar de minutos a segundos, multiplica por 60.':`Para convertir ${math(ut(d.unit))} a ${math(ut(d.siUnit))}, multiplica por ${math(num(units[d.unit][1]))}.`).join(' ')}`;render(root);return;}
  root.querySelector('.conversion-feedback').innerHTML='<span class="good">✓ Datos listos en unidades SI.</span>';convert.querySelectorAll('input,button').forEach(x=>x.disabled=true);const box=root.querySelector('.formula-stage');box.innerHTML=`<h4>Elige la relación despejada para ${math(r.target)}</h4><div class="answers formula-choices"></div><p class="formula-feedback" role="status"></p>`;
  r.options.forEach(t=>{const b=document.createElement('button');b.type='button';b.innerHTML=math(t);b.setAttribute('aria-label',t);b.onclick=()=>{if(t!==r.rearranged){box.querySelector('.formula-feedback').textContent='Revisa qué variable buscas y qué datos tienes. Puedes volver a elegir.';return;}box.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add('correct');box.querySelector('.formula-feedback').innerHTML='<span class="good">✓ La relación corresponde a los datos y a la incógnita.</span>';answerStage();};box.querySelector('.answers').append(b);});render(root);
 };
 function answerStage(){const area=root.querySelector('.answer-stage');area.innerHTML=`${r.prep.map(formula).join('')}<h4>Sustituye y calcula</h4>${formula(r.substitution)}<form class="result-form"><label>${math(r.target)} = <input name="result" aria-label="Resultado numérico" inputmode="decimal" required autocomplete="off"></label><label>Unidad <select name="unit" aria-label="Unidad del resultado" required><option value="">Elige</option>${['N','A','C','s','V','Ω','W','J'].map(u=>`<option value="${u}">${u}</option>`).join('')}</select></label>${r.interaction?'<label>Interacción <select name="interaction" aria-label="Interacción de las cargas" required><option value="">Elige</option><option>Atracción</option><option>Repulsión</option></select></label>':''}<button type="submit">Comprobar respuesta</button></form><p class="answer-feedback" role="status"></p>`;
  area.querySelector('form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,v=parse(form.elements.result.value);if(!Number.isFinite(v)){area.querySelector('.answer-feedback').textContent='Escribe un número decimal o científico válido.';return;}const ok=close(v,r.answer)&&form.elements.unit.value===r.unit&&(!r.interaction||form.elements.interaction.value===r.interaction);area.querySelector('.answer-feedback').innerHTML=`<span class="${ok?'good':'retry'}">${ok?'✓ ¡Correcto!':'Revisa el valor, la unidad y, cuando corresponda, la interacción. Puedes corregirlos.'}</span>`;root.querySelector('.solution-stage').innerHTML=fullSolution(r);render(root);};render(root);
 }
 render(root);
}
