import {P,constant,latex,mathML,rationalTex,rationalML,evaluate} from './algebra.mjs';
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderMath(tex,ml){if(globalThis.katex)try{return `<span class="formula">${globalThis.katex.renderToString('\\displaystyle '+tex,{throwOnError:true,strict:'error',trust:false,output:'htmlAndMathml'})}</span>`;}catch{}return `<span class="formula"><math xmlns="http://www.w3.org/1998/Math/MathML" displaystyle="true">${ml}</math></span>`;}
export const math=(e,vars,values)=>renderMath(latex(e,vars,values),mathML(e,vars,values));
export const num=v=>renderMath(rationalTex(v),rationalML(v));
export function equation(left,right,vars,values=null){return renderMath(`${latex(P(left),vars,values)}=${rationalTex(right)}`,`<mrow>${mathML(P(left),vars,values)}<mo>=</mo>${rationalML(right)}</mrow>`);}
export const pair=(values,vars)=>renderMath(vars.map((v,i)=>`${v}=${rationalTex(values[i])}`).join(',\\quad '),`<mrow>${vars.map((v,i)=>`${i?'<mo>,</mo>':''}<mi>${esc(v)}</mi><mo>=</mo>${rationalML(values[i])}`).join('')}</mrow>`);
export function expression(p,values=null){return p.kind==='system'?`<div class="equations">${p.equations.map(e=>equation(e.left,e.right,p.variables,values)).join('')}</div>`:math(p.original,p.variables,values);}
export const option=(p,i,values=null)=>p.kind==='system'?pair(p.options[i],p.variables):math(p.options[i],p.variables,values);
export const letters=['A','B','C','D'];
export function divisionReminder(){return `<div class="division-reminder"><svg viewBox="0 0 520 230" role="img" aria-label="Cociente encima de la barra; divisor a la izquierda; dividendo dentro de la caja; residuo debajo"><path d="M165 180 V70 H490" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><g fill="currentColor" font-family="Georgia, serif" font-size="30" text-anchor="middle"><text x="325" y="45">Cociente</text><text x="78" y="128">Divisor</text><text x="325" y="128">Dividendo</text><text x="325" y="205">Residuo</text></g></svg></div>`;}
function numericExpression(e,values){if(e.kind==='fraction'){const a=evaluate(e.n,values),b=evaluate(e.d,values);return renderMath(`\\frac{${rationalTex(a)}}{${rationalTex(b)}}`, `<mfrac>${rationalML(a)}${rationalML(b)}</mfrac>`);}if(e.kind==='sum')return e.items.map((i,j)=>`${i.sign<0?' − ':j?' + ':''}${numericExpression(i.node,values)}`).join('');return num(evaluate(e,values));}
export function trial(p,t,index){
  const values=pair(t.values,p.variables);
  if(p.kind==='system')return `<section class="trial"><header><h3>Prueba ${index}</h3>${values}</header><p>La pareja debe cumplir las dos ecuaciones.</p><div class="system-trial">${p.equations.map((e,i)=>`<div class="trial-card"><strong>Ecuación ${i+1}</strong>${equation(e.left,e.right,p.variables)}<span class="flow-arrow" aria-hidden="true">↓</span>${equation(e.left,e.right,p.variables,t.values)}<span class="flow-arrow" aria-hidden="true">↓</span><div class="numeric-line">${num(t.equations[i].left)} <span>${t.equations[i].match?'=':'≠'}</span> ${num(e.right)}</div><p>${t.equations[i].match?'✓ Se cumple.':'No se cumple con esta pareja.'}</p></div>`).join('')}</div></section>`;
  const division=t.division;
  const matches=t.matches.map(i=>letters[i]);
  let hint=matches.length===1?`La opción ${matches[0]} coincide con el problema para esta prueba.`:matches.length>1?`Las opciones ${matches.join(' y ')} coinciden en esta prueba. Prueba otros valores.`:'Ninguna opción coincide en esta prueba.';
  return `<section class="trial"><header><h3>Prueba ${index}</h3>${values}</header><div class="trial-card original-trial"><strong>Problema</strong>${expression(p)}<span class="flow-arrow" aria-hidden="true">↓</span>${expression(p,t.values)}<span class="flow-arrow" aria-hidden="true">↓</span><div class="numeric-line">${numericExpression(p.original,t.values)} <span>=</span> ${num(t.original)}</div>${division?`<div class="division-values"><p>Dividendo: ${num(division.dividend)} · Divisor: ${num(division.divisor)}</p><p>${p.asked==='quotient'?'Residuo':'Cociente'} para comprobar: ${math(p.given||P(p.R),p.variables)} → ${math(p.given||P(p.R),p.variables,t.values)} = ${num(division.companion)}</p></div>`:''}</div><div class="trial-options">${p.options.map((o,i)=>`<div class="trial-card"><strong>${letters[i]})</strong>${option(p,i)}<span class="flow-arrow" aria-hidden="true">↓</span>${option(p,i,t.values)}<span class="flow-arrow" aria-hidden="true">↓</span>${t.options[i]?num(t.options[i]):'<p>No está definida para estos valores. Esto solo describe esta prueba.</p>'}${division&&t.options[i]?`<div class="identity-check"><p>Divisor × Cociente + Residuo</p><div class="numeric-line">${num(division.divisor)} × ${num(p.asked==='quotient'?t.options[i]:division.companion)} + ${num(p.asked==='quotient'?division.companion:t.options[i])} = ${num(division.checks[i])}</div><p>${t.matches.includes(i)?'✓ Coincide con el dividendo en esta prueba.':'No coincide con el dividendo en esta prueba.'}</p></div>`:''}</div>`).join('')}</div><p class="trial-hint">${hint}</p>${t.collision?'<p class="collision-note">Con estos valores algunas opciones coinciden entre sí. Otra sustitución puede darte más información.</p>':''}<p class="proof-note">Una coincidencia numérica no demuestra una identidad algebraica.</p></section>`;
}
