import {versions,practice,steps,correct,chooseVersion} from './modelo.mjs';
import {illustratedDiagram} from './figuras.mjs';
const app=document.querySelector('#app'),mode=document.querySelector('main').dataset.mode;
const base=new URL('../',import.meta.url);
const link=(path)=>new URL(path,base).href;
const math=t=>`<span class="math" data-tex="${t}">${t}</span>`;
function render(){app.querySelectorAll('[data-tex]').forEach(el=>{if(window.katex)window.katex.render(el.dataset.tex,el,{throwOnError:false});});}
window.addEventListener('load',render);
function focus(){app.querySelector('h2')?.focus();}
function diagram(q,labels=false){
 if(q.scene!=='plain')return illustratedDiagram(q);
 const val=k=>labels?({a:'a · cateto',b:'b · cateto',c:'c · hipotenusa'}[k]):`${q.missing===k?'?':q[k]} ${q.scene==='plain'?'cm':'m'}`;
 const scene={tree:'<path d="M85 240V65" stroke="#957148" stroke-width="16"/><circle cx="85" cy="65" r="43" fill="#b6d8a6"/>',ladder:'<path d="M75 250V40H45" fill="none" stroke="#c5bacf" stroke-width="16"/><path d="M94 58L307 232" stroke="#e6ab49" stroke-width="17"/>',park:'<rect x="85" y="60" width="220" height="180" fill="#d8ecc4" stroke="#8cab7b" stroke-dasharray="6 5"/>',tent:'<path d="M85 60V240H45Z" fill="#f2cc84"/>',ramp:'<path d="M85 60L305 240H85Z" fill="#ded7f1"/>'}[q.scene]||'';
 return `<svg viewBox="0 0 410 300" role="img" aria-label="Triángulo rectángulo: cateto horizontal ${val('a')}, cateto vertical ${val('b')}, hipotenusa diagonal ${val('c')}."><path d="M35 242H345" stroke="#ddd" stroke-width="3"/>${scene}<path d="M85 60V240H305Z" fill="${q.scene==='plain'?'#edf5fb':'none'}" stroke="#385a79" stroke-width="4"/><path d="M85 222H103V240" fill="none" stroke="#385a79" stroke-width="2"/><g class="svg-label"><text x="196" y="274" text-anchor="middle">${val('a')}</text><text x="45" y="153" text-anchor="middle" transform="rotate(-90 45 153)">${val('b')}</text><text x="226" y="137" text-anchor="middle" transform="rotate(39 226 137)">${val('c')}</text></g></svg>`;
}
function menu(){app.innerHTML=`<p class="lead">Dos lados conocidos. Un lado por descubrir.</p><div class="hero"><div><span class="badge">UNA SESIÓN CORTA</span><h2>Pequeños pasos, grandes descubrimientos</h2><p>Aprende a sustituir, calcular y usar una raíz. Después, lleva la fórmula a una aventura.</p><a class="btn" href="${link('explicacion/index.html')}">Comenzar →</a></div>${diagram({scene:'plain'},true)}</div><div class="menu-cards"><a href="${link('explicacion/index.html')}"><span>01 · DESCUBRE</span><h2>La fórmula en tres pasos</h2><p>Hipotenusa o cateto: tú eliges.</p></a><a href="${link('ejercicios/lado-faltante/index.html')}"><span>02 · PRACTICA</span><h2>Cuatro pequeños retos</h2><p>Sustituye y encuentra el lado faltante.</p></a><a href="${link('juegos/misiones-pitagoricas/index.html')}"><span>03 · JUEGA</span><h2>Misiones de Pitágoras</h2><p>Tres aventuras posibles. Cuatro niveles por partida.</p></a></div>`;render();}
let page=0,unknown='c',revealed=0;
function lesson(){
 const q={a:3,b:4,c:5,missing:unknown,scene:'plain'};
 const content=[`<h2 tabindex="-1">1. Encuentra el ángulo recto</h2><p>El cuadradito marca ${math('90^\\circ')}. Los lados que se juntan ahí son los <strong>catetos</strong>. El lado de enfrente es la <strong>hipotenusa</strong>: el más largo.</p>${diagram(q,true)}<p class="notice">Usamos Pitágoras solo en triángulos rectángulos.</p>`,`<h2 tabindex="-1">2. Eleva, combina y saca raíz</h2><div class="big-math">${math('a^2+b^2=c^2')}</div><p>Para la <strong>hipotenusa</strong>, suma los cuadrados. Para un <strong>cateto</strong>, resta a la hipotenusa al cuadrado el otro cateto al cuadrado.</p><div class="formula-pair">${math('c=\\sqrt{a^2+b^2}')}${math('a=\\sqrt{c^2-b^2}')}</div><p>La raíz deshace el cuadrado. Por ejemplo, ${math('\\sqrt{25}=5')}, porque ${math('5^2=25')}.</p>`,`<h2 tabindex="-1">3. Sustituye los valores</h2><div class="actions"><button type="button" data-unknown="c" aria-pressed="${unknown==='c'}">Buscar hipotenusa</button><button type="button" data-unknown="b" aria-pressed="${unknown==='b'}">Buscar cateto</button></div><div class="two-col">${diagram(q)}<div><p>${unknown==='c'?'Conoces los dos catetos: suma sus cuadrados.':'Conoces la hipotenusa y un cateto: resta sus cuadrados.'}</p>${steps(q).slice(0,revealed).map((s,i)=>`<div class="step"><small>${['SUSTITUYE','CALCULA LOS CUADRADOS','SACA LA RAÍZ POSITIVA'][i]}</small>${math(s)}</div>`).join('')}${revealed<3?'<button class="btn" id="reveal">Mostrar siguiente paso</button>':'<p class="success">¡Listo! La longitud es positiva.</p>'}</div></div>`];
 app.innerHTML=`<div class="panel">${content[page]}<div class="actions">${page?'<button id="back">← Anterior</button>':''}${page<2?'<button class="btn" id="continue">Continuar →</button>':`<a class="btn" href="${link('ejercicios/lado-faltante/index.html')}">Continuar a los ejercicios →</a>`}</div></div>`;
 app.querySelector('#continue')?.addEventListener('click',()=>{page++;lesson();focus();});app.querySelector('#back')?.addEventListener('click',()=>{page--;lesson();focus();});
 app.querySelectorAll('[data-unknown]').forEach(b=>b.onclick=()=>{unknown=b.dataset.unknown;revealed=0;lesson();app.querySelector(`[data-unknown="${unknown}"]`).focus();});app.querySelector('#reveal')?.addEventListener('click',()=>{revealed++;lesson();app.querySelector('#reveal')?.focus();});render();
}
let index=0,version=chooseVersion(),cases=[],solved=false;
function start(){index=0;cases=mode==='game'?versions[version].levels:Array.from({length:4},(_,i)=>practice(i));round();}
function round(){
 solved=false;const q=cases[index];
 app.innerHTML=`<div class="progress-head"><span class="badge">${mode==='game'?versions[version].name:'Entrenamiento'}</span><span>${mode==='game'?'Nivel':'Ejercicio'} ${index+1} de 4</span></div><progress max="4" value="${index}" aria-label="Retos completados">${index}/4</progress><section class="panel"><h2 tabindex="-1">${q.title}</h2><p class="question">${q.text}</p><div class="two-col"><div>${diagram(q)}<p class="caption">Dibujo de referencia, no a escala. Suelo horizontal y ángulo recto.</p></div><div><p class="badge">BUSCA ${q.missing==='c'?'LA HIPOTENUSA':'UN CATETO'}</p><form id="answer-form"><label for="answer">Longitud que falta</label><div class="answer-row"><input id="answer" name="answer" type="text" inputmode="decimal" autocomplete="off" required aria-describedby="feedback"><span>${mode==='game'?'m':'cm'}</span></div><button class="btn" type="submit">Comprobar</button></form><p id="feedback" role="status" aria-live="polite"></p><details><summary>Necesito una ayuda</summary><p>${q.missing==='c'?'Suma los cuadrados de los dos catetos y saca la raíz.':'Resta los cuadrados: hipotenusa menos el cateto conocido. Después saca la raíz.'}</p>${math(q.missing==='c'?'c=\\sqrt{a^2+b^2}':`${q.missing}=\\sqrt{c^2-${q.missing==='a'?'b':'a'}^2}`)}</details><div id="solution"></div><button class="btn next" id="next" hidden>${index===3?'Terminar':'Continuar →'}</button></div></div></section>`;
 app.querySelector('form').onsubmit=e=>{e.preventDefault();if(solved)return;const input=app.querySelector('#answer');const feedback=app.querySelector('#feedback');if(!correct(input.value,q[q.missing])){feedback.textContent='Todavía no. Revisa qué lado buscas, calcula los cuadrados y recuerda sacar la raíz.';feedback.className='notice';input.setAttribute('aria-invalid','true');return;}solved=true;input.readOnly=true;input.removeAttribute('aria-invalid');app.querySelector('[type=submit]').disabled=true;feedback.textContent='¡Correcto! Problema resuelto.';feedback.className='success';app.querySelector('#solution').innerHTML=steps(q).map(s=>`<div class="step">${math(s)}</div>`).join('');app.querySelector('progress').value=index+1;app.querySelector('#next').hidden=false;render();app.querySelector('#next').focus();};
 app.querySelector('#next').onclick=()=>{if(!solved)return;if(++index===4)finish();else round();focus();};render();
}
function finish(){app.innerHTML=`<section class="panel celebration"><span class="medal" aria-hidden="true">✦</span><h2 tabindex="-1">${mode==='game'?'¡Misión cumplida, Kenia!':'¡Ya tienes la clave!'}</h2><p>Completaste los cuatro retos. Para la hipotenusa sumas; para un cateto restas. Al final, sacas la raíz.</p><div class="actions"><button class="btn" id="again">${mode==='game'?'Jugar otra aventura':'Otros cuatro ejercicios'}</button>${mode==='practice'?`<a class="btn" href="${link('juegos/misiones-pitagoricas/index.html')}">Continuar al juego →</a>`:''}</div></section>`;app.querySelector('#again').onclick=()=>{version=chooseVersion(version);start();focus();};}
if(mode==='menu')menu();else if(mode==='lesson')lesson();else start();
