export const NIVELES=[
 {id:'atomo',name:'Átomo',tag:'Una pieza de un elemento',color:'#6852a2',definition:'Es la unidad más pequeña que conserva la identidad de un elemento químico.',examples:['Carbono (C)','Oxígeno (O)','Hidrógeno (H)'],memory:'Átomo: una unidad de un elemento.',connection:'Los átomos pueden unirse mediante enlaces químicos para formar moléculas.',detail:'Dos átomos de hidrógeno y uno de oxígeno forman una molécula de agua.',hint:'Empieza por la unidad de un elemento, como un átomo de carbono.'},
 {id:'molecula',name:'Molécula',tag:'Átomos que se enlazan',color:'#18678a',definition:'Está formada por dos o más átomos unidos mediante enlaces químicos.',examples:['Agua (H₂O)','Glucosa','ADN'],memory:'Molécula: átomos unidos.',connection:'Muchas moléculas forman los materiales de las estructuras celulares, incluidos los organelos.',detail:'Una mitocondria contiene muchas moléculas diferentes, como proteínas y lípidos.',hint:'Después del átomo busca el nivel de los átomos unidos por enlaces.'},
 {id:'organelo',name:'Organelo',tag:'Un trabajo dentro de la célula',color:'#ae4267',definition:'Es una estructura dentro de una célula que cumple una función específica.',examples:['Mitocondria','Núcleo'],memory:'Organelo: una estructura con una tarea celular.',connection:'Los organelos forman parte de las células y colaboran en su funcionamiento.',detail:'Las mitocondrias ayudan a obtener ATP; el núcleo contiene la mayor parte del ADN de una célula animal.',hint:'Antes de la célula completa ubica una estructura que trabaja dentro de ella.'},
 {id:'celula',name:'Célula',tag:'Aquí está la unidad de la vida',color:'#196451',definition:'Es la unidad básica de la vida. Todo ser vivo tiene una o más células.',examples:['Célula muscular','Neurona'],memory:'Célula: unidad básica de la vida.',connection:'En organismos como una persona, células especializadas se organizan en tejidos.',detail:'Varias células musculares coordinan su trabajo en el tejido muscular.',hint:'Busca la unidad básica de la vida: contiene estructuras celulares y puede formar tejidos.'},
 {id:'tejido',name:'Tejido',tag:'Células que hacen equipo',color:'#a54a40',definition:'Es un conjunto organizado de células similares que colaboran en una función.',examples:['Tejido muscular','Tejido epitelial'],memory:'Tejido: células que trabajan juntas.',connection:'Distintos tejidos se combinan para formar un órgano.',detail:'El corazón incluye tejido muscular, nervioso y otros tejidos: no es solo un grupo de células iguales.',hint:'Las células similares se organizan antes de formar un órgano. ¿Qué nivel forman?'},
 {id:'organo',name:'Órgano',tag:'Varios tejidos, una función',color:'#a54767',definition:'Es una estructura formada por varios tejidos que trabajan en conjunto.',examples:['Corazón','Estómago','Hoja de una planta'],memory:'Órgano: varios tejidos coordinados.',connection:'Los órganos colaboran entre sí en sistemas o aparatos.',detail:'El corazón y los vasos sanguíneos colaboran en el sistema circulatorio.',hint:'Después del tejido busca una estructura formada por varios tejidos, como el corazón.'},
 {id:'sistema',name:'Sistema o aparato',tag:'Órganos que se coordinan',color:'#396a8e',definition:'Es un conjunto de órganos que colaboran para realizar funciones importantes.',examples:['Sistema digestivo','Sistema circulatorio'],memory:'Sistema o aparato: órganos que colaboran.',connection:'En una persona, distintos sistemas trabajan coordinadamente en el organismo completo.',detail:'El sistema digestivo incluye órganos como el estómago y los intestinos; el dibujo muestra el circulatorio.',hint:'Un órgano no trabaja solo: busca el nivel que reúne órganos relacionados.'},
 {id:'organismo',name:'Organismo',tag:'Un ser vivo completo',color:'#566b2f',definition:'Es un ser vivo individual. Puede estar formado por una sola célula o por muchas.',examples:['Persona','Perro','Planta','Bacteria'],memory:'Organismo: un ser vivo completo.',connection:'Llegaste al ser vivo completo. Ahora puedes recorrer sus niveles en sentido contrario.',detail:'En una persona se coordinan distintos sistemas. Una bacteria ya es un organismo con una sola célula, sin tejidos ni órganos.',hint:'El último nivel de este recorrido es el ser vivo completo.'}
];
const q=(id,categoryId,prompt,correct,others,explanation)=>({id,categoryId,prompt,correctId:'correcta',choices:[{id:'correcta',text:correct},...others.map((text,i)=>({id:'otra-'+i,text}))],explanation});
export const PREGUNTAS=[
 q('a1','atomo','¿Cuál es la unidad más pequeña que conserva la identidad de un elemento químico?','Átomo',['Molécula','Célula'],'Un átomo conserva la identidad de un elemento. Una molécula reúne átomos y una célula contiene muchas moléculas.'),
 q('a2','atomo','Tienes una sola unidad del elemento carbono. ¿Qué estás describiendo?','Un átomo',['Un tejido','Un organelo'],'Un átomo de carbono es una unidad de ese elemento; un tejido y un organelo tienen una organización mucho más compleja.'),
 q('a3','atomo','Una molécula de agua tiene dos H y un O. ¿Qué representa cada una de esas tres piezas?','Un átomo',['Una célula','Un órgano'],'H y O representan hidrógeno y oxígeno. En una molécula de agua hay tres átomos unidos.'),
 q('m1','molecula','¿Qué puede formarse cuando dos o más átomos se unen mediante enlaces químicos?','Una molécula',['Un tejido','Un sistema'],'Los enlaces químicos unen átomos en moléculas. No basta juntar átomos para obtener directamente un tejido o un sistema.'),
 q('m2','molecula','El agua, la glucosa y el ADN son ejemplos de…','Moléculas',['Órganos','Células'],'Aunque tienen tamaños y funciones diferentes, los tres están formados por átomos unidos químicamente.'),
 q('m3','molecula','¿Qué descripción corresponde a una molécula?','Átomos unidos mediante enlaces químicos',['Células similares que colaboran','Órganos coordinados'],'Una molécula se describe por sus átomos y enlaces. Las otras descripciones corresponden a un tejido y a un sistema.'),
 q('g1','organelo','¿Dónde se encuentran organelos como las mitocondrias?','Dentro de las células',['Fuera de todo ser vivo','Entre órganos, sin formar parte de células'],'Los organelos son estructuras celulares. Las mitocondrias se encuentran dentro de las células que las poseen.'),
 q('g2','organelo','Una estructura dentro de una célula ayuda a obtener ATP. Es una mitocondria. ¿Qué nivel representa?','Organelo',['Órgano','Organismo'],'La mitocondria tiene una tarea dentro de la célula. No es un órgano ni un ser vivo completo.'),
 q('g3','organelo','El núcleo es parte de una célula animal. ¿Cómo lo clasificas?','Como un organelo',['Como un tejido','Como un sistema'],'El núcleo es una estructura celular con funciones específicas; un tejido reúne células y un sistema reúne órganos.'),
 q('c1','celula','¿Cuál es la unidad básica de la vida?','La célula',['El átomo','El sistema'],'Todo ser vivo está formado por una o más células. Átomos y moléculas forman sus materiales, pero no son por sí solos unidades vivas.'),
 q('c2','celula','¿Qué tienen en común una persona, una planta y una bacteria?','Están formadas por una o más células',['Todas tienen corazón','Todas tienen muchos sistemas'],'La organización celular es común a todos los seres vivos. Una bacteria tiene una sola célula y no tiene órganos.'),
 q('c3','celula','En el recorrido de menor a mayor organización, ¿qué viene después de organelo y antes de tejido?','Célula',['Órgano','Molécula'],'Los organelos son partes de células; en organismos como una persona, las células se organizan en tejidos.'),
 q('t1','tejido','Células musculares organizadas colaboran para contraerse. En conjunto forman…','Tejido muscular',['Una molécula','Un organelo'],'Un tejido reúne células especializadas que colaboran en una función, como la contracción.'),
 q('t2','tejido','¿Qué distingue a un tejido de un órgano?','El tejido agrupa células; el órgano combina varios tejidos',['El tejido agrupa órganos; el órgano agrupa átomos','Son dos nombres para el mismo nivel'],'Tejido y órgano son niveles distintos: las células forman tejidos y varios tejidos forman un órgano.'),
 q('t3','tejido','¿Cuál completa la secuencia célula → ___ → órgano?','Tejido',['Sistema','Átomo'],'El tejido es el nivel entre célula y órgano. Después del órgano viene sistema o aparato.'),
 q('o1','organo','El corazón combina varios tejidos que colaboran para bombear sangre. Es un…','Órgano',['Organelo','Tejido único'],'El corazón contiene varios tipos de tejidos. Por eso es un órgano, no un organelo ni un único tejido.'),
 q('o2','organo','¿Qué se forma cuando varios tejidos se organizan en una estructura con una función?','Un órgano',['Una molécula','Un átomo'],'Los tejidos se combinan en órganos, como el estómago o el corazón.'),
 q('o3','organo','Una hoja tiene varios tejidos que colaboran en sus funciones. ¿A qué nivel pertenece?','Órgano',['Molécula','Organelo'],'Las plantas también tienen órganos. Una hoja está formada por diferentes tejidos.'),
 q('s1','sistema','El estómago y los intestinos colaboran en la digestión. Juntos forman parte de un…','Sistema o aparato',['Organelo','Átomo'],'El sistema o aparato digestivo reúne órganos que colaboran en la digestión y la absorción de nutrientes.'),
 q('s2','sistema','¿Qué nivel está entre órgano y organismo en nuestro recorrido?','Sistema o aparato',['Célula','Tejido'],'Los órganos se coordinan en sistemas o aparatos, y en una persona estos colaboran en el organismo completo.'),
 q('s3','sistema','Corazón y vasos sanguíneos colaboran para transportar sangre. ¿Qué representa ese conjunto?','Sistema circulatorio',['Una sola célula','Una molécula'],'Es un sistema porque varias estructuras de nivel órgano colaboran en una función del cuerpo.'),
 q('v1','organismo','¿Cuál es el nivel de mayor organización entre estas opciones?','Organismo',['Célula','Átomo'],'De estas opciones, organismo representa al ser vivo completo. No significa que siempre sea grande: también hay organismos microscópicos.'),
 q('v2','organismo','Una bacteria está formada por una sola célula. ¿También es un organismo?','Sí: es un ser vivo completo',['No: le falta tener órganos','Solo si forma un tejido'],'Una bacteria es un organismo unicelular: una célula realiza sus funciones vitales. No necesita tejidos, órganos ni sistemas.'),
 q('v3','organismo','¿Qué grupo contiene únicamente ejemplos de organismos completos?','Persona, perro y planta',['Corazón, núcleo y agua','Tejido muscular, ADN y átomo'],'Persona, perro y planta son seres vivos completos. Los otros grupos contienen partes o materiales de los seres vivos.')
];
